### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by RDahle** [emuPlace/emuThreeDS#10]
I may be stupid, but how do i use it?😅 how can i open the downloaded files and stuff like that?

**Comment by subwxxfer** [comment]
> I didnt understand shit😂 is there a detailed tutorial anywhere?😅

That was detailed lmao

**Comment by eliu9395** [comment]
I put a rom in the /rom folder, but it doesn't show up when I open emuthreeds.

**Comment by xdccrlz** [comment]
The specified discord server is unavailable. It is necessary to place the instructions for using and configuring the application in an accessible place. otherwise, it is impossible to understand whether the application is working or not.

**Comment by eliu9395** [comment]
> The specified discord server is unavailable. But experience is our comrade: 1. must use decrypted roms (*.3ds), 2. play with jit/hle settings. Good luck!

Thanks, that works! Also, is there a way to install game updates?
