### ISSUE TITLE
[1.0.6.1] App crashes upon opening

### ISSUE THREAD

**Issue by CoolPeachGaming** [emuPlace/emuThreeDS#109]
https://github.com/emuPlace/emuThreeDS/assets/90976594/612b3922-11b1-4806-8e55-4ec5e0a3eada

Sideloaded with TrollStore 1.5.1
Jailbroken with Dopamine 1.0.5
iOS Version: 15.3.1
iPhone SE 2020

**Comment by mjd180** [comment]
The minimum iOS version appears to have been raised to 16, starting with 1.0.6.1. While TrollStore will install it (unlike SideStore/AltStore) on iOS 15, it will just crash on open (e.g. 15.2.1).
