### ISSUE TITLE
App crashes when I press emulation

### ISSUE THREAD

**Issue by ChromaOfficial** [emuPlace/emuThreeDS#111]
I also can’t see any folders in my files app besides “rom” 

I’m using the latest IPA version and Enabled dev mode on my iphone 11

**Comment by ChromaOfficial** [comment]
I found the folder but I can't open my Ultra Sun in the emu3ds app as it just doesnt show up and whenever I press "emulation", the app just crashes

**Comment by CycloKid** [comment]
maybe try powering off your phone, then powering it back on.

**Comment by CycloKid** [comment]
also roms NEED to be placed in the roms directory

**Comment by ChromaOfficial** [comment]
Its currently in this folder. Is that correct?
![13b6b025-3a03-4b8e-9f34-5676d1c05f4c](https://github.com/emuPlace/emuThreeDS/assets/135223236/e1156c0d-3806-42e3-8fa8-b19576f665e7)

**Comment by ChromaOfficial** [comment]
This is me opening the app. The crashing occurs whenever I press "emulation" 

Uploading WhatsApp Video 2023-06-01 at 8.37.52 PM.mp4…

**Comment by JIMMY523elcrak** [comment]
I play The Pokémon ultra sun and The MH un The previos versión bit now when i emulate them it crashes

**Comment by Maxounin** [comment]
> Its currently in this folder. Is that correct? ![13b6b025-3a03-4b8e-9f34-5676d1c05f4c](https://user-images.githubusercontent.com/135223236/242598314-e1156c0d-3806-42e3-8fa8-b19576f665e7.jpg)

You have to unzip this archive and put the file from inside into the roms folder

**Comment by official-antique** [comment]
Piracy is not allowed under any circumstance. Please don't discuss it here or in Discord.
