### ISSUE TITLE
trollstore crashing

### ISSUE THREAD

**Issue by BigManCole** [emuPlace/emuThreeDS#12]
installed with trollstore 15.1.1, crashing on open

**Comment by bu7nty101** [comment]
trollstore isnt supported as of 1.0.3, later updates will add support for trollstore

**Comment by memito23** [comment]
> trollstore isnt supported as of 1.0.3, later updates will add support for trollstore

Oh that's too bad as TrollStore is able to enable JIT support without Jitstreamer or without jailbreak

**Comment by memito23** [comment]
> > > trollstore isnt supported as of 1.0.3, later updates will add support for trollstore
> > 
> > 
> > Oh that's too bad as TrollStore is able to enable JIT support without Jitstreamer or without jailbreak
> 
> That’s incorrect.

How so?

i use DolphiniOS and it enables JIT with Trollstore, no jailbreak and no jitstreamer needed

**Comment by mjd180** [comment]
> > > > trollstore isnt supported as of 1.0.3, later updates will add support for trollstore
> > > 
> > > 
> > > Oh that's too bad as TrollStore is able to enable JIT support without Jitstreamer or without jailbreak
> > 
> > 
> > That’s incorrect.
> 
> How so?
> 
> i use DolphiniOS and it enables JIT with Trollstore, no jailbreak and no jitstreamer needed

Then there’s something incredibly unique about your configuration &/or something you're not mentioning. Up until mid/late last year, TrollStore wouldn’t even let you inject JIT. Now it does allow you, but it certainly doesn’t just open the sandbox entitlements for you.

Forgive me for asking what seems like a dumb question, but you’ve actually tried to play a game on DolphinIOS, right (the app itself doesn’t require JIT, just the games)?

**Comment by memito23** [comment]
You need the new Beta’s of Dolphinios as they added JIT support for TrollStore on the 4.0 Betas. The app won’t even run if you don’t enable JIT at the beginning, when installed with TrollStore, it enables JIT and games play full speed no problem
