### ISSUE TITLE
Will Backbone controllers be compatible?

### ISSUE THREAD

**Issue by eramo607** [emuPlace/emuThreeDS#13]
Is this emulator going to be compatible with a BackBone controller? Because emulators like the Delta Emulator is AltStore is able to use it, and it works completely well. Even the Dolphin Emulator can allow us to use a Backbone. So I’m wondering if it’s possible to do the same with a 3DS emulator so I can play games on the emulator effectively.

**Comment by bu7nty101** [comment]
all controllers that ios supports via bluetooth should be compatible with emuthreeds, although u can ask antique for compatibility with the backbone controller, no idea how those work

**Comment by official-antique** [comment]
Hey @eramo607, all controllers should be supported out of the box if Apple supports them (PS4, Xbox, Joy-cons (iOS 16+)). Closing for now as its old.
