### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by EGNL** [emuPlace/emuThreeDS#14]
Folders, JIT, rom name; everything should be correct and set up. And even without all these things the app should at least open.

ips file:

exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: (_objc_claimAutoreleasedReturnValue)","Referenced from: '\/Volumes\/VOLUME\/*\/emuThreeDS.app\/Frameworks\/SDL2.framework\/SDL2'","Expected in: '\/usr\/lib\/libobjc.A.dylib'"]},

It seems to be an SDL framework issue.

Device: iPad Air 2019 (Gen 3)
iPadOS Version: 15.6.1
Program used for installation: Sideloadly
JIT Enabler: JitStreamer

I also previously posted the ips file in the Discord server.

**Comment by jershell** [comment]
I have same error.
How to reproduce. 
1. Install simulator with iphone7 and select ios 15.5(need download before).
2. Select `relese` for `run` 
3. Press the run button and have the error.
