### ISSUE TITLE
Virtual and physical controller issue needs fixing and help 

### ISSUE THREAD

**Issue by ansinerd** [emuPlace/emuThreeDS#141]
Dear Antique, first of all I wanna thank you for your amazing work. You are quite talented and the ios gaming community owes you a lot.

Here I wanna mention one persistent issue and suggest you to speak to either Oatmeal dome or some other dev or UI designer who can help you figure out controller issue.
Its fine that 3ds works with currently implemented touch and virtual controllers even in absence of dpad, but you aim to port Vita3k to iOS as well and I suppose it would also be plagued with similar touch controller issue, it would be using Right and Left stick, as well as dpad, R and L as well. 
U would face issues even then, I hope you speak to someone or may be check out codes of those who have made better touch controllers like oatmeal for dolphinios or may be ppsspp team cause their implementation is perhaps the best on ios.
Solving controller layout issue would help you with 3ds, vita3k and even more emulators like plays2 that you aim to bring in future.

Thank you so much

**Comment by kkkkggbn** [comment]
In terms of updates, the author is really better than play! The author is much faster, but the progress of optimization has not been up
