### ISSUE TITLE
bug i found in this emulator

### ISSUE THREAD

**Issue by apie08** [emuPlace/emuThreeDS#145]
> cannot control the volume

> game need to start again after minimize

> opacity for control

> layout touch controller need to adjust and revamp

> function to exit game and go to list game menu

> emulator cannot run game after enable JIT

> no LR 1:x for layout landscape like DS player

make fix 30 fps minimum

overall, this is the best emulator even it has alot of bug with iphone 14 pro max IOS 16

**Comment by JTPVR2** [comment]
I strongly agree with the volume issue. Still trying to figure that out 🥲
