### ISSUE TITLE
I can’t add games or click emulation

### ISSUE THREAD

**Issue by DamagedS23** [emuPlace/emuThreeDS#146]
When I click the plus button nothing happens. When I click emulation it crashes.

**Comment by Rocketj22** [comment]
Man did u resolve this kind of bug? I'm having the same problem

**Comment by JTPVR2** [comment]
> Man did u resolve this kind of bug? I'm having the same problem

I can't tell you how to download games for the emulator but I can tell you how to add them. Drag your game file to the emuthreeds file folder on the " On My IPhone" Tab on the files app. Then, inside the emuthreeds folder, drag it to roms. After that, exit the app and restart the emuthreeds app if it's already open. If it's not open, just open the app. Your game should be there.

**Comment by JTPVR2** [comment]
> Man did u resolve this kind of bug? I'm having the same problem

Remember, you need to unzip your game file. Also, to use the emulation button, press a game you want to play then press emulation.

**Comment by NuclearNova26** [comment]
I may be missing something but I have my file unzipped (it is a cxi) and I put it into my emuthreeds roms folder. When I go to open emuthreeds again nothing is in the library. Any idea as to why that might be?
