### ISSUE TITLE
Needs Tilt Action For Games Like Kirby

### ISSUE THREAD

**Issue by JTPVR2** [emuPlace/emuThreeDS#148]
This is an issue and an idea, in games that require tilt like Kirby: Triple Deluxe, you need to tilt to get pass the level. This is a bummer and I’m wondering if you guys should add a tilt function to the app. If so then that will be great!

**Comment by DoxhundDude** [comment]
I literally gave up playing that game because of that stupid fire that blocked my path.

**Comment by JTPVR2** [comment]
> I literally gave up playing that game because of that stupid fire that blocked my path.

Yeah, I’m hoping they might add a tilt action like dolphinIOS.

**Comment by DoxhundDude** [comment]
Me too, maybe there could be buttons to tilt right left up down etc if the phone accelerometer doesn’t work with the emulator.

**Comment by JTPVR2** [comment]
> Me too, maybe there could be buttons to tilt right left up down etc if the phone accelerometer doesn’t work with the emulator.

Agreed.
