### ISSUE TITLE
JIT keeps crashing but HLE works perfectly.

### ISSUE THREAD

**Issue by Eli0213** [emuPlace/emuThreeDS#15]
When I click on JIT and save and go in one of my games, it initially crashes, but when I use it on HLE it works perfectly. Any reason why JIT crashes and only JIT but not HLE?

**Comment by SkilledScript** [comment]
Did you enable JIT on the app beforehand with Jitstreamer or Altstore?

**Comment by Eli0213** [comment]
Now it works but I can’t do Jitstreamer because every time I open the Jitstreamer pair on my computer it instantly kicks me out and it won’t even let me type in a number. It so fucking annoying. If I can’t type in a number to set up Jitstreamer then I have to get my computer, the cable, my phone, and then go to ALT store to enable JIT. Is there anyway you can help me, with the problem how it kicks me out instantly. Or do you know any way I can enable JIT without the help with a computer?And thanks for your help.

**Comment by DzXAnt22** [comment]
same issue with me, I launch the app, enable JIT through altstore, enable JIT in app settings, save settings, and as soon as I tap on the game it instantly closes.

**Comment by wyldcrd** [comment]
Jitstreamer is down, but i get the issue even when i enable through altstore
