### ISSUE TITLE
New super mario 2 crash shortly

### ISSUE THREAD

**Issue by meLuvMbape** [emuPlace/emuThreeDS#150]
Im trying to play new super mario 2 but it crash shortly after i enter the game ,this is my first time using this emulator

**Comment by Alexck002** [comment]
Did you activate JIT?

**Comment by meLuvMbape** [comment]
no cuz when i use jit it wont let me start the game,i just use hle(idk what is this but it let me start the game)

**Comment by meLuvMbape** [comment]
ok so i have da fix,just do not turn on hw shader and also jit if you have the same problem as me

**Comment by Hinatai** [comment]
I recommend to turn on the HLE option.

**Comment by meLuvMbape** [comment]
thanks blud
