### ISSUE TITLE
Controls and other things

### ISSUE THREAD

**Issue by NurK41** [emuPlace/emuThreeDS#151]
Hi everyone,I'm glad to see that the emulator is way better now!
but I have to tell some things:
1)make language settings
2)change virtual Joystick,to make it similar to the citra virtual joystick(btw can someone tell me what are all those white buttons? I don't know how to use them)
3)add some more settings for everything(emu,system[with the time],screen,graphics...)

It changed a lot,and is really better now!
Last thing,can someone tell me how to download the newest versions?on changelog I see there is even 1.0.65,mine is 1.0.63,but I don't see them on the files download page .

Thx everyone:)

**Comment by NurK41** [comment]
ANOTHER THING!IN THIS VERSION I CANNOT CHANGE THE AUDIO VOLUME ANYMORE,PLEASE FIX :)

**Comment by Hinatai** [comment]
v1.0.6.3 is the latest releases for github which is free, and v1.0.6.4 is released on buymeacoffee page → https://www.buymeacoffee.com/antique but it is paid. You need $5 canary tier to get one. Also v1.0.6.4 fixed audio issues. Antique said emuThreeDS is using Apple’s official onscreen controller GCcontroller, so it can’t be changed that much and to make a onscreen controller look like Citra, it needs a new custom controller which can’t be made that easily. For language settings I agree but I’m sure Antique will add it later on the development. v1.0.6.4 added tons of new settings but it doesn’t have time setting but it does have custom texture settings, render settings etc. v1.0.6.5 which is said on changelog is just a plan for the next release and not available yet.
