### ISSUE TITLE
Volume issue

### ISSUE THREAD

**Issue by Simplistic223** [emuPlace/emuThreeDS#152]
In 1.0.6.3 i cant control the volume it just goes to max volume and cant mute it

**Comment by ntaraku2** [comment]
1.0.6.4 fixed this issue

**Comment by JTPVR2** [comment]
How do we get 1.0.6.4?

> 1.0.6.4 fixed this issue

**Comment by ntaraku2** [comment]
> How do we get 1.0.6.4?
> 
> 
> 
> > 1.0.6.4 fixed this issue
> 
> 
> 
> 

It's available for canary members here 

https://www.buymeacoffee.com/antique/emuthreeds-v1-0-6-4-available-canary-tier-members

**Comment by mjd180** [comment]
Is there anyway to mitigate the volume problem? It is such a bad bug that it renders the emulator, essentially, completely unusable for the non-deaf community.
