### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Gepporlotl** [emuPlace/emuThreeDS#154]
I had 5 problems with the app:
1- Whenever i have to type something (for example in Tomodachi Life where you have to name your island) the app crashes.
2- When i have to create a Mii the app crashes.
3- If i rotate the screen the controls disappear.
4- In landscape i can’t use the bottom of the touch screen because there are the library, emulation and settings buttons.
5- In portrait the screen glitches (you can see that in the image).
![IMG_0006](https://github.com/emuPlace/emuThreeDS/assets/89992814/7ace6c67-8a3f-4240-88b8-b2525153bd89)

**Comment by Hinatai** [comment]
This may help you with the problem with Tomodachi life. Check the guide here.
https://emuthreeds.wixsite.com/guide/post/how-to-fix-the-keyboard-crash-error-and-the-mii

Maybe change the Layout setting for the screen problem but either way portrait mode still has the controller glitch.
