### ISSUE TITLE
Canary v1.0.6.5 wishlist

### ISSUE THREAD

**Issue by ansinerd** [emuPlace/emuThreeDS#158]
Reminder to Antique since he is reverting back to swift from swift ui.

These features need to be implemented 
1. Resizeable customised controlle (size is too big for phones, its intrusive)
2. Double check volume issue
3. Save n load state
4. Dpad / thumb stick toggle
5. Background app close issues fix (vulkan disconnect)
6. Latest codes of citra official
7. Backbone controller support
8. Toggle to make on screen controls disappear
9. Cia file installation

**Comment by Hinatai** [comment]
Fixing Volume issue and toggling to make on-screen controller disappear is already done in v1.0.6.4. And ZL and ZR is only available for physical controller right now so maybe in the future this can be implemented too.
