### ISSUE TITLE
Requirements to be able to use JiT?

### ISSUE THREAD

**Issue by Sashanahuel11** [emuPlace/emuThreeDS#163]
I can't activate the option on my iPhone XR.
Is there a requirement?
I'm new and I don't speak English, I hope someone has the solution, thank you for reading.

**Comment by CharlieKreig** [comment]
> I can't activate the option on my iPhone XR.
> 
> Is there a requirement?
> 
> I'm new and I don't speak English, I hope someone has the solution, thank you for reading. 

Насколько я понимаю не обязателен jit, но с ним работает значительно лучше эмулятор
До Джейла активировал его через jitstreamer,не знаю есть ли более удобные способы

**Comment by Sashanahuel11** [comment]
Thank you, I'm going to see what I can do since I don't have a PC. Again, thank you for answering, I'm a novice and I don't understand much but I'm 23 years old and I have to be able to understand these things since I've been emulating for 10 years and I should be able to understand, at least basic aspects.
Exactly, I'm trying pokemon e inazuma eleven go 2. The games run to me at 15fps In the best of cases, and since I don't understand much, I want to inform myself so that I can solve it.

**Comment by CharlieKreig** [comment]
> Thank you, I'm going to see what I can do since I don't have a PC. Again, thank you for answering, I'm a novice and I don't understand much but I'm 23 years old and I have to be able to understand these things since I've been emulating for 10 years and I should be able to understand, at least basic aspects.
> Exactly, I'm trying pokemon e inazuma eleven go 2. The games run to me at 15fps In the best of cases, and since I don't understand much, I want to inform myself so that I can solve it.

Yeah, on iOS emulation some harder, then usual. With jit many games fully playable. I play Pokémon Ultra Sun with good resolution and smooth fps(I think more, then 40). But with last update touch screen working bad and screens deformed on iPad, but I believe, after some updates I can play on my iPad, like new 2ds xxl:)

**Comment by CharlieKreig** [comment]
![image](https://github.com/emuPlace/emuThreeDS/assets/99195826/c6c17d23-3008-426a-b5b9-917d5d833e85)

**Comment by Sashanahuel11** [comment]
Well, I'm glad to know that a good emulation is possible.
Yes, from what I was reading, there is an improved version that you have to pay for which is more advanced and does not have these window problems.
While I'm trying to be able to turn my iPhone into something similar to you new 2ds xxl.
Thank you for everything, friend
