### ISSUE TITLE
My critique of version 1.0.6.4

### ISSUE THREAD

**Issue by MarshtompMods** [emuPlace/emuThreeDS#166]
So I tested out the public release of 1.0.6.4 and I wanted to type my critique of it. I know you're chill Antique, so I have no fear that you'll take any of my criticisms as attacks. Your work on this emulator has been incredible, and I just wanted to lay some ideas out so that it will be even better in the future.

I know I suggested the ability to have customizable controls for physical controllers in the past, but I had no idea that it was possible to do so inside of iOS itself, so I wanted to say thanks for bringing that to my (and others in the Discord as well) attention. Now I can finally use emuThreeDS comfortably using the layout of an actual 3DS. In the meantime, this is a great substitute until emuThreeDS gets native button remapping.
I've also seen people say that there is no cheat support for emuThreeDS, but just because there is no GUI, doesn't mean there's no support. Cheats and mods work great if you know how to use Citra. For my testing, I tried some games with cheats, some games with mods, and some games vanilla.

Now for the actual critiques themselves:
- I'll start with this one because you've acknowledged it before and said it will be fixed soon, but the DPad doesn't work on physical controllers, only the control stick.
- The yellow Emulation text on the bottom of the screen is slightly obtrusive when playing in landscape, especially when in single-screen mode. If in a future version, the settings could be moved to the gear in the top left instead of the bottom right as it is now, there would be no need to have the yellow text on the bottom which would lead to a cleaner experience.
- Top left gear options: In previous versions of the app, there were gear options that aren't available in the current version of 1.0.6.4. These include Save States, amiibo, Control Stick to DPad (for virtual controllers), and exiting the game. Personally the most important one to me was the exit button since you could play another game without killing the app and having to re-enable JIT through a debugger like with SideStore every time you wanted to play another game. Hopefully all these top left gear options can return in the future, but if one comes first, I'm rooting for the exit button.

Out of the 5 games I tested, I have 2 game-specific critiques (these 2 games were played without cheats or mods):
- Pushmo is unfortunately completely unplayable. Any time a level is selected, the app crashes. On Rinsuki's Citra port, Pushmo worked perfectly fine and that's where I imported my save file from. I could start with a fresh save, but I'm not sure if that's the issue. I tried messing with the app's settings, but nothing I did made the game work properly.
- When playing Zelda: A Link Between Worlds, the graphics flicker often. This is not the case on Citra for PC. I could also test it on Rinsuki's Citra, but I don't remember how it performs there.

Over time, I'll test more games to see how compatibility is. I know some people said NSMB2 crashed as soon as they entered a level, I haven't tested that game, but I will later as well as others. I'll be sure to test more obscure games that I have as well since I'm sure the more popular games are being covered by others.

Thanks so much for reading my thoughts, Antique. I'm super impressed with this release and can't wait for this emulator to get better and better as time goes on!

**Comment by JTPVR2** [comment]
Can you try the Kirby Robobot game on the newest version? On the third level, the game would crash at the star at the end of the train. I want to see if it doesn’t crash anymore in the newest version. Please test this out.

**Comment by JTPVR2** [comment]
Also when do new versions come out officially without the subscription?

**Comment by MarshtompMods** [comment]
After further testing, I wanted post more of my findings here so that they could possibly be used as good data. I'll start with the app-wide findings, and then go to the game-specific ones.

- When using a controller, it is possible to disable the on-screen controls, thank you by the way for that, Antique. One little quirk happens with that though, as if you ever rotate the device from landscape into portrait, either by accident or to use the touch screen more easily, the on screen controls pop back up and you will need to disable them every time you rotate your device. I unfortunately don't have any coding experience, but I hope that this is a simple bug that can be easily fixed as it looks that way to my unexperienced eye.
- As my second and last app-wide critique, whenever emuThreeDS is closed or if the iDevice is put to sleep, either by inactivity or by simply pressing the power button, the game will be closed and the app will be reset. I checked this with DolphiniOS and it doesn't seem to be a JIT issue as that app uses JIT as well. Hopefully emuThreeDS can be saved in the background in case you ever need to close the app for something like sending a text.

As for the game-specific findings:
- Mario and Donkey Kong: Minis on the Move, Captain Toad: Treasure Tracker, and Crashmo all have the same problem as Pushmo, that being they're all unfortunately completely unplayable due to not being able to enter any level without crashing. I can't write this off as an eShop game issue as BOXBOY and Steamworld Dig both work, where Captain Toad, a cartridge game, doesn't.
- Kirby Planet Robobot crashes periodically at random spots in the game. Usually when playing the level twice though, it doesn't crash again in the same spot.
- Upon further testing, Zelda: A Link Between Worlds' visuals don't flicker any more, the shaders may have just had to cache for a little bit.
- NSMB2 worked perfectly for me, those saying it crashed when entering a level may have been playing on an outdated version or had weird settings.

I hope this update as well as the original post is helpful, Antique. I'm really enjoying emuThreeDS now and I'm looking forward to what it's like in the future!

**Comment by OOFB0I** [comment]
“Cheats and mods work great if you know how to use Citra.” I don’t understand how to use cheats could you explain I feel really stupid to ask. T^T
