### ISSUE TITLE
low ios version

### ISSUE THREAD

**Issue by KWK083** [emuPlace/emuThreeDS#17]
Can't I use it on a lower ios version.

**Comment by duckfromdiscord** [comment]
@KWK083 what version are you on, and what version do you need?

**Comment by KWK083** [comment]
I use ios 15. is it possible to use this emulator on iphone7plus?

**Comment by duckfromdiscord** [comment]
not sure how fast it'll be but you can try. the latest ipa build in git, https://github.com/emuPlace/emuThreeDS/releases/download/1.0.4/emuThreeDS_1.0.4_Test.ipa supports 15.0 at minimum.

**Comment by Joeybologna88** [comment]
Why is iOS 15 minimum?  What couldn’t be supported on jailbroken or troll store ios 14?

**Comment by KWK083** [comment]
I installed the ipa file on my iphone7plus but it doesn't work. I don't know that is the file's problem or the device can't open it.

**Comment by 1seam1** [comment]
I would also need support for a lower ios version. I use 13.6 and cant update past that. Using an Iphone 8+. I'd love to try this emulator out!

**Comment by official-antique** [comment]
@KWK083, iOS 15 is required at the moment for GCVirtualController which is Apple's native virtual controller. iOS 14 can only be supported if a custom controller is created but at this time that isn't in the works.
