### ISSUE TITLE
can’t play games because of crashing 

### ISSUE THREAD

**Issue by murd3rhouse** [emuPlace/emuThreeDS#171]
app usually crashes when trying to load any game. enabling JIT via my macbook can prevent this issue but id have to do this every time which is inconvenient. despite enabling JIT and getting it to run, games are unplayable since the on screen controls don’t work and the screen is stretched out.

**Comment by JIMMY523elcrak** [comment]
Yes

**Comment by YeetMaddox** [comment]
Same

**Comment by Zoobmaball** [comment]
Get sidestore
