### ISSUE TITLE
Games appear with the message invalid region

### ISSUE THREAD

**Issue by Choibi** [emuPlace/emuThreeDS#172]
When I try to add the ROM of Pokemon sapphire into the Tom folder and I open the app the game appear in the menu with the message 'invalid region' bellow and I can't launch it. What am I supposed to do please HELP.

**Comment by NikauM** [comment]
You are using the wrong file type. If it's a .cia file you need to decrypt it to a .cci file. There is a tutorial on YouTube.

**Comment by notcreepers** [comment]
If you're using a 3ds file, make sure it's not encrypted. Either redump the game decrypted or dump your AES keys. Citra's site can help you with both of these things.

**Comment by woah047** [comment]
I am using a .3ds file and have the same issue with the same game what do I do?
