### ISSUE TITLE
v1.0.6.5 (1) Issues

### ISSUE THREAD

**Issue by laucllaucl** [emuPlace/emuThreeDS#176]
| testing device: | iPhone 13 (iOS 16.5) |
|---|---|

issues:
| # | Description |
|---|---|
| 1. | L/R butttons disappeared |
| 2. | -/+ buttons not working |
| 3. | joystick Y-axis reversed |
| 4. | no exit button |

![IMG_1566](https://github.com/emuPlace/emuThreeDS/assets/20439361/6ff20872-49df-4a12-8cfa-fd23290ea29d)

> comments:
It would be nice to have the virtual controller Connect/Disconnect button and the Settings page back, thanks.
Thanks for your great work again.

**Comment by JTPVR2** [comment]
Wow

**Comment by JTPVR2** [comment]
I will wait for the next next update but is the settings changed?

**Comment by laucllaucl** [comment]
> I will wait for the next next update but is the settings changed?

No Settings page for the version I tested so no configurable settings.

**Comment by JTPVR2** [comment]
Oh
