### ISSUE TITLE
How to  use it?

### ISSUE THREAD

**Issue by zappythepikachu** [emuPlace/emuThreeDS#179]
I already downloaded the file

**Comment by luislaws2019** [comment]
How do I download the emuThreeDs on my iPhone

**Comment by JTPVR2** [comment]
Go to the releases and download the ipa file. After that, download AltStore from your computer to your phone on the AltStore website then sideload the ipa you downloaded and you should be done. Look up how to sideload ipa files with AltStore on YouTube for more information.

**Comment by JTPVR2** [comment]
If you don't have a computer, download the ipa file of any version on the releases tab and look up scarlet app on Google. After that, open the scarlet website with the red icon that looks like a S and press "get scarlet" at the bottom of the page. You might get taken to a ad, if so then delete the tab of that ad and press the download again. You will be taken to a page that shows different downloads. Press Direct Download. It will say open iTunes, Press open. After that press install profile. Go to settings, General, VPN, and verify the profile. You should be able to sideload the ipa and use emuThreeDS.

**Comment by JTPVR2** [comment]
If you want to download games for emuThreeDS, look up 3DS ROM's and download any game you like. After that, put the file in the files app, On My IPhone, emuThreeDS, ROM's. You should be done after and you can play any game of your choice. Good luck!

**Comment by Zoobmaball** [comment]
> If you want to download games for emuThreeDS, look up 3DS ROM's and download any game you like. After that, put the file in the files app, On My IPhone, emuThreeDS, ROM's. You should be done after and you can play any game of your choice. Good luck!

You're not supposed to tell people to pirate games lol

**Comment by JTPVR2** [comment]
> > If you want to download games for emuThreeDS, look up 3DS ROM's and download any game you like. After that, put the file in the files app, On My IPhone, emuThreeDS, ROM's. You should be done after and you can play any game of your choice. Good luck!
> 
> You're not supposed to tell people to pirate games lol

My bad lol
