### ISSUE TITLE
App crashes when game try’s to open keyboard

### ISSUE THREAD

**Issue by Redd12345** [emuPlace/emuThreeDS#18]
I’m playing the legend of Zelda: triforce heroes and it runs great! However when I get to an area where the game would normally open the 3ds keyboard to type in the game, the app crashes immediately. I would assume this happens in other games too.

**Comment by helynnekiwaii** [comment]
Yup happens in Tomodachi Life when I’m about to write my Island name. I’m sure it’ll get patched in 1.0.6

**Comment by helynnekiwaii** [comment]
Actually, maybe a bluetooth keyboard would work? Since Emuthreeds is in it’s beta stages, ios keyboard prob isnt implemented yet. I’ll see if i can try with a bluetooth keyboard. Hope this helps!

**Comment by Redd12345** [comment]
keyboard isnt added yet. ive been talking with dev

**Comment by helynnekiwaii** [comment]
gotcha, thank you for this info! I'll close my own issue.

**Comment by Redd12345** [comment]
did the bluetooth keyboard work?

**Comment by Redd12345** [comment]
tysm for the great idea!

**Comment by official-antique** [comment]
@Redd12345, the latest 1.0.5.4 did fix the issue but also caused problems for controllers, keyboard support should be done in 1.0.6 soon.
