### ISSUE TITLE
I can't play

### ISSUE THREAD

**Issue by Valtaoi0007** [emuPlace/emuThreeDS#181]
I managed to install Emuthreeds, downloaded the 3DS file and moved it to the right place, yet I can't open the game as it keeps crashing, I can't open the game and neither click on the emulation tab.

I use an iphone 13 pro and it is an IOS 16.5.1

**Comment by Valtaoi0007** [comment]
I found out the mistake myself, go to settings and disable the setting called "Use new 3ds", the game continued to work, if any more problems happen I will update this

**Comment by Valtaoi0007** [comment]
The game's opening is very slow, and the selection menu keeps changing between speeding up and slowing down, is there anything I need to turn on or off to reduce this?

**Comment by laucllaucl** [comment]
> The game's opening is very slow, and the selection menu keeps changing between speeding up and slowing down, is there anything I need to turn on or off to reduce this?

try enable JIT for emuthreeds via AltServer

**Comment by JTPVR2** [comment]
Yes, Enable JIT and make the settings like this, ![image](https://github.com/emuPlace/emuThreeDS/assets/135991726/ca630969-35db-4bb2-bcf5-3736fb37eabe)

**Comment by JTPVR2** [comment]
And this ![image](https://github.com/emuPlace/emuThreeDS/assets/135991726/547c7a7d-aa6d-4d9e-93e6-e83ae8c46808)
