### ISSUE TITLE
Mario and Luigi Superstar Saga Crashing 

### ISSUE THREAD

**Issue by gabezilla52** [emuPlace/emuThreeDS#183]
I'm playing on a 2022 iPad pro with the M2 chip on version 1.0.6.4. For one thing, I can't click the emulation tab before I start the game or else it crashes. However it does start when I pick it from the library. The game runs smoothly, and I am able to get through the tutorial fight with bowser, however after the tutorial fight when Bowser starts his dialog the game crashes at this spot each time without fail. 

Here are the logs:

[ 0.047379] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:LoadHeader:160: 16384 [ 0.047608] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:LoadHeader:160: 16384 [ 0.047741] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:LoadHeader:160: 16384 [ 0.051716] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:LoadHeader:160: 16384 [ 1.555094] Audio.DSP <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/audio_core/hle/hle.cpp:Impl:145: No decoder found, this could lead to missing audio [ 2.297524] RPC_Server <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/rpc/rpc_server.cpp:RPCServer:12: Starting RPC server ... [ 2.298059] RPC_Server <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/rpc/rpc_server.cpp:HandleRequestsLoop:113: Request handler started. [ 2.298150] RPC_Server <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/rpc/rpc_server.cpp:RPCServer:16: RPC started. [ 2.305317] Service.HTTP <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/http_c.cpp:DecryptClCertA:807: ClCertA file missing [ 2.306830] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_platform.cpp:operator():111: Candidate instance extension VK_KHR_portability_enumeration is not available [ 2.307810] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:CreateDevice:608: Geometry shaders not availabe! Accelerated rendering not possible! [ 2.307884] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_swapchain [ 2.307886] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_image_format_list [ 2.307887] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_pipeline_creation_feedback unavailable. [ 2.307889] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_EXT_shader_stencil_export [ 2.307891] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_timeline_semaphore [ 2.307893] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_portability_subset [ 2.307894] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_KHR_dynamic_rendering [ 2.307895] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_extended_dynamic_state unavailable. [ 2.307897] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_custom_border_color unavailable. [ 2.307898] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():633: Extension VK_EXT_index_type_uint8 unavailable. [ 2.307899] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:operator():625: Enabling extension: VK_EXT_pipeline_creation_cache_control [ 2.318860] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:496: Format B8G8R8Unorm unsupported, falling back unconditionally to R8G8B8A8Unorm [ 2.318867] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:496: Format X8D24UnormPack32 unsupported, falling back unconditionally to D32Sfloat [ 2.318869] Render.Vulkan <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_instance.cpp:CreateFormatTable:496: Format D24UnormS8Uint unsupported, falling back unconditionally to D32SfloatS8Uint [ 2.319805] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_resource_pool.cpp:Allocate:128: Allocating new descriptor pool [ 2.329156] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Upload buffer with size 131072 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached } [ 2.329321] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Download buffer with size 16384 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached } [ 2.329426] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 128 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached } [ 2.388020] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 65536 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached } [ 2.388120] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 4096 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached } [ 2.388168] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 2048 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached } [ 2.388211] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_stream_buffer.cpp:CreateBuffers:165: Creating Stream buffer with size 2048 KB with flags { DeviceLocal | HostVisible | HostCoherent | HostCached } [ 2.388707] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/renderer_vulkan.cpp:ReportDriver:1117: VK_DRIVER: MoltenVK 0.2.2012 [ 2.388709] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/renderer_vulkan.cpp:ReportDriver:1118: VK_DEVICE: Apple M2 GPU [ 2.388709] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/renderer_vulkan.cpp:ReportDriver:1119: VK_VERSION: 1.2.250 [ 2.389840] Core <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/telemetry_session.cpp:GetTelemetryId:48: failed to open telemetry_id: /var/mobile/Containers/Data/Application/696DB622-63AF-4D75-B8AB-FDF40C3EA747/Documents/config/telemetry_id [ 2.389891] Loader <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/loader/ncch.cpp:Load:215: Program ID: 00040000001B8F00 [ 2.389920] Service.FS <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:OpenFile:129: Failed to open /var/mobile/Containers/Data/Application/696DB622-63AF-4D75-B8AB-FDF40C3EA747/Documents/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/001b8f00/content/00000000.app [ 2.409039] Loader <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/kernel/process.cpp:ParseKernelCaps:151: ExHeader kernel version: 2.52 [ 2.410202] Service.CFG <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/cfg/cfg.cpp:SetPreferredRegionCodes:761: Preferred region code set to 1 [ 2.411412] Service.SRV <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/sm/srv.cpp:RegisterClient:63: (STUBBED) called. Caller PID=11 [ 2.415292] Service.SRV <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/sm/srv.cpp:EnableNotification:85: (STUBBED) called [ 2.415784] Service.NDM <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ndm/ndm_u.cpp:OverrideDefaultDaemons:186: (STUBBED) bit_mask=0x0000000F [ 2.415793] Service.NDM <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ndm/ndm_u.cpp:SuspendDaemons:74: (STUBBED) bit_mask=0x00000006 [ 2.415934] Service.APT <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/apt/apt.cpp:NotifyToWait:338: (STUBBED) app_id=768 [ 2.416096] Service.APT <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/apt/apt.cpp:AppletUtility:637: (STUBBED) called command=0X00000007, input_size=0X00000004, output_size=0X00000001 [ 2.416168] Service.APT <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/apt/apt.cpp:AppletUtility:637: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001 [ 2.416524] Service.FS <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/fs/fs_user.cpp:InitializeWithSdkVersion:599: (STUBBED) called, version: 0x0B0502C8 [ 2.416575] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default [ 2.416616] Input <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/frontend/input.h:CreateDevice:91: Unknown engine name: motion_emu [ 2.416822] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default [ 2.427501] Service.LDR <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRR:155: (STUBBED) called, crr_buffer_ptr=0x08015000, crr_size=0x00001000 [ 2.433463] Service.DSP <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/audio_core/hle/hle.cpp:LoadComponent:502: Firmware hash: 0x60af809bc5b32916 [ 2.433465] Service.DSP <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/audio_core/hle/hle.cpp:LoadComponent:506: Structures hash: 0x3fe31c7be0d849ca [ 2.433466] Service.DSP <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/dsp/dsp_dsp.cpp:LoadComponent:192: called size=0x35388, prog_mask=0x000300FF, data_mask=0x003500FF [ 2.433532] Service.DSP <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/dsp/dsp_dsp.cpp:RegisterInterruptEvents:258: Registered interrupt=2, channel=2, event=event-00114a6c [ 2.433544] Service.DSP <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/dsp/dsp_dsp.cpp:GetSemaphoreEventHandle:274: (STUBBED) called [ 2.433558] Service.DSP <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/dsp/dsp_dsp.cpp:SetSemaphoreMask:284: (STUBBED) called mask=0x2000 [ 2.433577] Audio.DSP <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/audio_core/hle/hle.cpp:PipeWrite:261: Application has requested initialization of DSP hardware [ 2.433589] Service.DSP <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000 [ 2.433928] Service.DSP <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/dsp/dsp_dsp.cpp:SetSemaphore:57: called, semaphore_value=4000 [ 2.555395] Service.GSP <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/gsp/gsp_gpu.cpp:AcquireRight:748: called flag=00000000 process=11 thread_id=0 [ 2.557464] Kernel.SVC <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/kernel/svc.cpp:CreateMemoryBlock:1695: called addr=0x004B5000 [ 2.557472] Kernel.SVC <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/kernel/svc.cpp:CreateMemoryBlock:1695: called addr=0x004B7000 [ 2.557528] Service.APT <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/apt/apt.cpp:CheckNew3DSApp:1160: (STUBBED) called [ 2.812795] Service.APT <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/apt/apt.cpp:AppletUtility:637: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001 [ 2.815559] Service.FS <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/archive_ncch.cpp:OpenFile:159: Shared Font file missing. Loading open source replacement from memory [ 2.831521] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default [ 2.923261] Service.LDR <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ldr_ro/cro_helper.cpp:ApplyStaticAnonymousSymbolToCRS:555: CRO "EtcSys" exports 0 static anonymous symbols [ 2.929178] Service.LDR <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:331: CRO "EtcSys" loaded at 0x004DE000, fixed_end=0x0054D000 [ 2.929889] Service.LDR <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ldr_ro/cro_helper.cpp:ApplyStaticAnonymousSymbolToCRS:555: CRO "Title" exports 0 static anonymous symbols [ 2.929934] Service.LDR <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ldr_ro/ldr_ro.cpp:LoadCRO:331: CRO "Title" loaded at 0x0054E000, fixed_end=0x00550000 [ 3.870287] Render.Vulkan <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/video_core/renderer_vulkan/vk_resource_pool.cpp:Allocate:128: Allocating new descriptor pool [ 5.698936] Service.FS <Warning> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/fs/file.cpp:OpenLinkFile:214: (STUBBED) File command OpenLinkFile Path: [Binary: 000000000000000000000000] [ 7.779104] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:LoadHeader:160: 16384 [ 7.779293] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:LoadHeader:160: 16384 [ 7.779425] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/ncch_container.cpp:LoadHeader:160: 16384 [ 10.564608] Service.LDR <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ldr_ro/ldr_ro.cpp:UnloadCRO:369: Unloading CRO "EtcSys" [ 10.564965] Service.LDR <Info> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/hle/service/ldr_ro/ldr_ro.cpp:UnloadCRO:369: Unloading CRO "Title" [ 13.360152] Service.FS <Error> /Users/antique/Desktop/emuthreeds/emuThreeDS/citra_core/core/file_sys/archive_backend.h:GetOpenDelayNs:193: Delay generator was not initalized. Using default

**Comment by MarioLC1** [comment]
I also have this issue and I have no idea how to fix it

**Comment by MarioLC1** [comment]
it also happens on bowsers inside story but at the part where bowser gets the "lucky" shroom every time
