### ISSUE TITLE
Game/emulator crashing

### ISSUE THREAD

**Issue by LASTRESORT76** [emuPlace/emuThreeDS#189]
I dont know if i did something wrong or missed something when setting up the emulator but the game i want to play instantly crashes the emulator, i even enabled JIT. If someone can help me out i would appreciate it.

**Comment by JTPVR2** [comment]
> I dont know if i did something wrong or missed something when setting up the emulator but the game i want to play instantly crashes the emulator, i even enabled JIT. If someone can help me out i would appreciate it.

What game is it? Sonic and the lost world?

**Comment by LASTRESORT76** [comment]
Inazuma eleven go chronostone wildfire. Like it instantly crashes, i even tried mario and sonic, same thing..

**Comment by JTPVR2** [comment]
> Inazuma eleven go chronostone wildfire. Like it instantly crashes, i even tried mario and sonic, same thing..

What IOS Version are you on?

**Comment by JTPVR2** [comment]
The only versions that fully support emuthreeds is all the iOS with 16 like 16.3.1, 16.5.1 etc.. all the other versions work but they are buggy.

**Comment by JTPVR2** [comment]
It can also depend on what version you downloaded on this app. The newest version works as of right now for iOS 16.3.1. I also have a question, ![image](https://github.com/emuPlace/emuThreeDS/assets/135991726/6ada26e7-e62c-4612-9edc-3581e6cd7781) out of all of these games, have you tried them with your crashing issue?

**Comment by LASTRESORT76** [comment]
I am on the latest ios update. Sooo  and i only tried the sonic game in that list, and mario kart, inazuma eleven chronostone wildfire all 3 crashes. Add me on discord if you wanna talk much easier . My discord tagg is _lastresort

**Comment by JTPVR2** [comment]
> I am on the latest ios update. Sooo  and i only tried the sonic game in that list, and mario kart, inazuma eleven chronostone wildfire all 3 crashes. Add me on discord if you wanna talk much easier . My discord tagg is _lastresort

Alright

**Comment by JIMMY523elcrak** [comment]
it happens too me too with Monster hunter and Pokémon ultra sun

**Comment by hoangkm13** [comment]
do you find the solution yet

**Comment by JIMMY523elcrak** [comment]
Nop
