### ISSUE TITLE
Sound issues.

### ISSUE THREAD

**Issue by cuttchi** [emuPlace/emuThreeDS#191]
I can’t seem to be able to turn the volume off. Doesn’t matter how loud my device is, the volume of the emulator won’t change. Using headphones doesn’t work either.

**Comment by JTPVR2** [comment]
> I can’t seem to be able to turn the volume off. Doesn’t matter how loud my device is, the volume of the emulator won’t change. Using headphones doesn’t work either. 

Try using the newest version.
