### ISSUE TITLE
enabling JIT makes game crash on start

### ISSUE THREAD

**Issue by Luilli1** [emuPlace/emuThreeDS#195]
so i just downloaded emuthreeds and installed monster hunter 4, but whenever i tried to launch the game it crashed, and when i disable JIT it doesnt, pd. i dont really know what JIT is so i want to ask, is it better to play without it? does enabling it makes it so it takes more effort to run it? (sorry for my bad english)

**Comment by JTPVR2** [comment]
> so i just downloaded emuthreeds and installed monster hunter 4, but whenever i tried to launch the game it crashed, and when i disable JIT it doesnt, pd. i dont really know what JIT is so i want to ask, is it better to play without it? does enabling it makes it so it takes more effort to run it? (sorry for my bad english)

JIT is important to use. If you have AltStore, enable JIT from the app. JIT is used for faster emulation so do enable the JIT option and run it from AltStore. Look up how to enable JIT on YouTube.

**Comment by Luilli1** [comment]
ok so i know how to enable JIT now, but will i always need to have my ios device connected to my pc in order to enable JIT? because it wont let me enable it unless its connected, also how can i use a bluetooth keyboard for the app?

**Comment by JTPVR2** [comment]
> ok so i know how to enable JIT now, but will i always need to have my ios device connected to my pc in order to enable JIT? because it wont let me enable it unless its connected, also how can i use a bluetooth keyboard for the app?

I'm not sure if we can Bluetooth a keyboard to emuthreeds but I do know how to enable JIT without using your computer all the time.

Method 1. You can try JitStreamer

Method 2. You can enable Wi-Fi Syncing on the iTunes app for your computer 

Method 3. You can use JitterBug (Jutterbug requires two iPhones each time you enable jit.)

I recommend you use JitStreamer. It's quick and easy. The only thing you need to do is pair your device to your computer once and your done. Look up how to use JitStreamer on YouTube. 

Btw you can only enable JIT with WiFi, not cellular data or hotspot. If there's anything else you need, add me on discord. My discord username is jtpvr. Good Luck!
