### ISSUE TITLE
Buttons block screen

### ISSUE THREAD

**Issue by Dragetize** [emuPlace/emuThreeDS#196]
Does anyone know how to make the buttons not block the game? iPhone 14 pro
![IMG_6500](https://github.com/emuPlace/emuThreeDS/assets/138502269/4ef5bf21-b9f2-43f5-95c7-fa9daacafe76)

**Comment by MarioLC1** [comment]
that version has forced max audio though

**Comment by JTPVR2** [comment]
On the newest version 1.0.6.4, there's settings. Go to the settings page and set these two settings to default. ![image](https://github.com/emuPlace/emuThreeDS/assets/135991726/a2ce5365-2597-47b3-bb0f-1ee602f0259d)
You should be able to see your game and your controls correctly.

**Comment by Dragetize** [comment]
> On the newest version 1.0.6.4, there's settings. Go to the settings page and set these two settings to default. ![image](https://user-images.githubusercontent.com/135991726/250649763-a2ce5365-2597-47b3-bb0f-1ee602f0259d.jpeg)
> You should be able to see your game and your controls correctly.



> On the newest version 1.0.6.4, there's settings. Go to the settings page and set these two settings to default. ![image](https://user-images.githubusercontent.com/135991726/250649763-a2ce5365-2597-47b3-bb0f-1ee602f0259d.jpeg)
> You should be able to see your game and your controls correctly.

Thank you, it worked

**Comment by JTPVR2** [comment]
> > On the newest version 1.0.6.4, there's settings. Go to the settings page and set these two settings to default. ![image](https://user-images.githubusercontent.com/135991726/250649763-a2ce5365-2597-47b3-bb0f-1ee602f0259d.jpeg)
> 
> > You should be able to see your game and your controls correctly.
> 
> 
> 
> 
> 
> 
> 
> > On the newest version 1.0.6.4, there's settings. Go to the settings page and set these two settings to default. ![image](https://user-images.githubusercontent.com/135991726/250649763-a2ce5365-2597-47b3-bb0f-1ee602f0259d.jpeg)
> 
> > You should be able to see your game and your controls correctly.
> 
> 
> 
> Thank you, it worked

Np
