### ISSUE TITLE
Increase Performance

### ISSUE THREAD

**Issue by NikauM** [emuPlace/emuThreeDS#197]
Is there a way or any settings that help to increase performance? My game is a bit slow and buggy.

**Comment by JTPVR2** [comment]
> Is there a way or any settings that help to increase performance? My game is a bit slow and buggy.

Yes, I have a setting that can help with your performance. ![image](https://github.com/emuPlace/emuThreeDS/assets/135991726/494ba89b-09bc-4e08-9c21-d94aa03f9e99)

**Comment by JTPVR2** [comment]
> Is there a way or any settings that help to increase performance? My game is a bit slow and buggy.

![image](https://github.com/emuPlace/emuThreeDS/assets/135991726/c180736e-406d-4e73-893d-15533d6ceed1)

**Comment by NikauM** [comment]
I'm playing Pokemon Ultra Sun and these settings did increase performance but it makes the game crash.

**Comment by MarioLC1** [comment]
me trying to play mario & luigi bowsers inside story or superstar saga: (they both crash)

**Comment by pantendo** [comment]
> I'm playing Pokemon Ultra Sun and these settings did increase performance but it makes the game crash.

It could possibly be because you enabled JIT. Try disabling it.
