### ISSUE TITLE
What file type

### ISSUE THREAD

**Issue by flamespro** [emuPlace/emuThreeDS#198]
Not problem but what file type does the emulator take because my 7z file isn’t working

**Comment by official-antique** [comment]
This emulator only supports the 4 main rom formats; .cci, .cia, .cxi and .3ds.

You appear to have pirated a rom as they never come in 7z legally, that also means that I nor anyone else will be able to assist further legally.

**Comment by flamespro** [comment]
Sorry for that and also thank you
