### ISSUE TITLE
Mii feature

### ISSUE THREAD

**Issue by flamespro** [emuPlace/emuThreeDS#199]
I got super Mario 3d land on the emulator but I don’t have any miis so when it asks to make a mii the app crashes

**Comment by JTPVR2** [comment]
Yeah, it's a feature that needs to be added

**Comment by JTPVR2** [comment]
> I got super Mario 3d land on the emulator but I don’t have any miis so when it asks to make a mii the app crashes

It's probably the most requested

**Comment by flamespro** [comment]
Oh dang
