### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by RDahle** [emuPlace/emuThreeDS#2]
When do you think it will be done? Cant wait man😊

**Comment by TrHedgehog** [comment]
Idk

**Comment by deformedRat** [comment]
This isn’t an issue, just be patient. Coding is hard

**Comment by Ayoendit** [comment]
We will be patient.
but I cant wait to play "Ace attorney 5".
Support to the creator ❤️

**Comment by official-antique** [comment]
Hey @RDahle, I can't give an exact date or time mostly because when I fix an issue others have appeared (video rendering > file system) but it is progressing quite well. I'll close the issue as it isn't exactly an issue.

**Comment by Ayoendit** [comment]
What does web service do?
idk.
Goodnight 🥚
