### ISSUE TITLE
App Crashes on iPhone 13. 15.0

### ISSUE THREAD

**Issue by CAArmy** [emuPlace/emuThreeDS#20]
The application crashes on iOS 15.0 using an iPhone 13. This is without Trollstore

I use Sideloadly

**Comment by official-antique** [comment]
@CAArmy, iOS 15 does seem to present a lot of issues when running the emulator, on all devices I've seen logs for it looks as though the issue is always memory related, I'll see if I've got an iOS 15 device around to test that with.
