### ISSUE TITLE
App not usable (crashs)

### ISSUE THREAD

**Issue by FakeAltF4** [emuPlace/emuThreeDS#201]
The app keeps crashing, ive tried installing the app via scarlet and trollstore but it didnt work, here is my issue :
App crashes when the « emulation » button is pressed. It doesnt even make a log ! The log file is just empty
Im on Iphone 8 ios 16.5.1 jb rootless with palen1x

**Comment by mjd180** [comment]
Phone not up to min spec?

**Comment by JTPVR2** [comment]
> The app keeps crashing, ive tried installing the app via scarlet and trollstore but it didnt work, here is my issue :
> 
> App crashes when the « emulation » button is pressed. It doesnt even make a log ! The log file is just empty
> 
> Im on Iphone 8 ios 16.5.1 jb rootless with palen1x

I don't know anything about the log but I do know how to fix your emulation crashing button. All you need to do is enable JIT in the settings tab, after that, enable it from AltStore. Now press a game on the library and press emulation. You should be good to go!

**Comment by FakeAltF4** [comment]
Hi, ive tried to use Altstore but it didnt work :( 
also, someone has the same problem as me and we both have an A11 bionic chip on ios 16.5.1 (iphone 8, 8+, X, Ipad 7th gen) maybe thats the issue...
https://en.wikipedia.org/wiki/Apple_A11

**Comment by FakeAltF4** [comment]
the person i'm talking about is Razery12 (Files and crashes #203)

**Comment by FakeAltF4** [comment]
i will try to unjailbreak my phone and reset it, if the app keeps crashing, that means there is an compatibility issue i will then try to upgrade ios to see if the issue is only with ios 16.5.1,

**Comment by mjd180** [comment]
I’d doubt it’s the iOS version that’s the problem.

**Comment by JTPVR2** [comment]
> i will try to unjailbreak my phone and reset it, if the app keeps crashing, that means there is an compatibility issue, i will then try to upgrade ios to see if the issue is only with ios 16.5.1, 

That's a good idea, people with jailbroken phones have issues with this app too.

**Comment by FakeAltF4** [comment]
> > i will try to unjailbreak my phone and reset it, if the app keeps crashing, that means there is an compatibility issue, i will then try to upgrade ios to see if the issue is only with ios 16.5.1,
> 
> That's a good idea, people with jailbroken phones have issues with this app too.

still crashes even after i removed my jailbreak, restored my phone and installed EmuThreeDS with AltStore
