### ISSUE TITLE
what games work and dont work can i have a list or a link to a website please

### ISSUE THREAD

**Issue by bluedivine9** [emuPlace/emuThreeDS#202]

**Comment by mjd180** [comment]
Don’t believe such a list exists yet. From personal experience, I’ll contribute "Star Fox 64 3D" & "Luigi's Mansion: Dark Moon".

**Comment by MarioLC1** [comment]
Mario and Luigi Bowsers Inside Story and Mario and Luigi Superstar Saga also don't work (both crash after the tutorial every time)
