### ISSUE TITLE
Files and crashes

### ISSUE THREAD

**Issue by Razery12** [emuPlace/emuThreeDS#203]
Whenever I tap the emulation button it always crashed  I’ve tried downloading it via AltStore scarlet and side store neither of them worked and when I checked the files there was only 1 file inside the emuthreeds file which was Roms and even if I tried putting roms inside of it it won’t work                  I have an iPhone X full up to date

**Comment by JTPVR2** [comment]
> Whenever I tap the emulation button it always crashed  I’ve tried downloading it via AltStore scarlet and side store neither of them worked and when I checked the files there was only 1 file inside the emuthreeds file which was Roms and even if I tried putting roms inside of it it won’t work                  I have an iPhone X full up to date

Try and download the newest version on EmuthreeDS and sideload it to AltStore.

**Comment by HNDZ963** [comment]
I have the same problem when I try to emulate it closes, and I have the latest version, and I have the same iPhone

**Comment by Razery12** [comment]
> > Whenever I tap the emulation button it always crashed  I’ve tried downloading it via AltStore scarlet and side store neither of them worked and when I checked the files there was only 1 file inside the emuthreeds file which was Roms and even if I tried putting roms inside of it it won’t work                  I have an iPhone X full up to date
> 
> Try and download the newest version on EmuthreeDS and sideload it to AltStore.

It didn’t work

**Comment by JTPVR2** [comment]
> > > Whenever I tap the emulation button it always crashed  I’ve tried downloading it via AltStore scarlet and side store neither of them worked and when I checked the files there was only 1 file inside the emuthreeds file which was Roms and even if I tried putting roms inside of it it won’t work                  I have an iPhone X full up to date
> 
> > 
> 
> > Try and download the newest version on EmuthreeDS and sideload it to AltStore.
> 
> 
> 
> It didn’t work

What IOS is your phone?

**Comment by Razery12** [comment]
> > > > Whenever I tap the emulation button it always crashed  I’ve tried downloading it via AltStore scarlet and side store neither of them worked and when I checked the files there was only 1 file inside the emuthreeds file which was Roms and even if I tried putting roms inside of it it won’t work                  I have an iPhone X full up to date
> > 
> > 
> > > 
> > 
> > 
> > > Try and download the newest version on EmuthreeDS and sideload it to AltStore.
> > 
> > 
> > It didn’t work
> 
> What IOS is your phone?

16.5.1

**Comment by JTPVR2** [comment]
That's weird.. maybe you need to upgrade your phone

**Comment by Razery12** [comment]
> That's weird.. maybe you need to upgrade your phone

Wdym

**Comment by CombatCat74** [comment]
I have the exact same issue. And I have JIT enabled so I don't think it's that. I also have the newest Update for everything.
