### ISSUE TITLE
what are some games that work 

### ISSUE THREAD

**Issue by bluedivine9** [emuPlace/emuThreeDS#204]
if anybody knows a game i can download and try just to see if the app works on my phone?

**Comment by official-antique** [comment]
Games must be dumped from a real device to be legal, no one can assist you if you are or want to download games illegally.

Any game should work as long as it’s .3ds, .cci, .cxi or .cia.

**Comment by bluedivine9** [comment]
no i have game i just want to know which one work on the emulator flawlessly
