### ISSUE TITLE
Will you consider incorporating your emulator code into Delta Emulator or AltStore?

### ISSUE THREAD

**Issue by SemiZeul21** [emuPlace/emuThreeDS#205]
Title says it all. Not really an issue, but a question. Delta is probably the most used emulator on iOS and putting it on the AltStore app along DolphiniOS and Provenance would probably promote your work, alongside making your work more accessible.

**Comment by JTPVR2** [comment]
> Title says it all. Not really an issue, but a question. Delta is probably the most used emulator on iOS and putting it on the AltStore app along DolphiniOS and Provenance would probably promote your work, alongside making your work more accessible.

This is genius for the owner fr

**Comment by official-antique** [comment]
Hey @SemiZeul2, 

I don’t personally have plans to make a Delta core but others are more than welcome to.

My plan for these emulators is really just to make them and learn along the way while giving something to the community.

**Comment by JTPVR2** [comment]
> Hey @SemiZeul2, 
> 
> I don’t personally have plans to make a Delta core but others are more than welcome to.
> 
> My plan for these emulators is really just to make them and learn along the way while giving something to the community.

I like That.
