### ISSUE TITLE
-Major Crashes/Issues-

### ISSUE THREAD

**Issue by CombatCat74** [emuPlace/emuThreeDS#209]
I have the app installed on my iPhone X with IOS 16.5.1. I have Kirby: Triple Deluxe in my library and JIT Enabled through AltStore. The app crashes when opening the game and clicking on the Emulation Button. I really want this fixed so I can use the app. If there is more information you need to fix this let me know.

**Comment by shiny6675** [comment]
Turn off jit and then it works fine
