### ISSUE TITLE
No Function At All

### ISSUE THREAD

**Issue by NuclearNova26** [emuPlace/emuThreeDS#210]
I'm running the latest version as of this post on a iPhone 12 Pro Max with IOS 16.5.1. 

Whenever I open the app Clicking the "+" button in Library does nothing and whenever I click the "Emulation" button in the middle of the screen on the bottom the app crashes.

Does anyone know of a fix for these issues? I have JIT enabled both through Alt Store and in the emuthreeds app, that did not solve my issues.

**Comment by gabezilla52** [comment]
You have to add the game in your files app, go to on my iPhone, emuThreeDS, roms, and then put the game there, it should be a .3ds format. Also, the settings only apply in the app when you close it, so to use jit, enable it in the app, then close it and open it up again, and then enable jit through alt store.

**Comment by NuclearNova26** [comment]
Thanks for the response, I know a lot of people post an issue and no one has an answer. I thought emuThreeDs could run cxi files, is there anyway to turn a .cxi into .3ds format? I got my file into the roms folder but I still see no games in the library section of emu. I am pretty new to all of this stuff so I'm slowly learning
