### ISSUE TITLE
EmuSwitch?

### ISSUE THREAD

**Issue by JTPVR2** [emuPlace/emuThreeDS#215]
@official-antique Will you continue the EmuSwitch project or is it abandoned?

**Comment by official-antique** [comment]
From my testing it just isn't possible right now (code & device specifications), everything minus the renderer code does seem to work fine but MoltenVK just doesn't support all of the required extensions for it to work. I'll probably only have 100% sure to work repositories for emulators on this organization just to not get hopes up.

**Comment by JTPVR2** [comment]
> From my testing it just isn't possible right now (code & device specifications), everything minus the renderer code does seem to work fine but MoltenVK just doesn't support all of the required extensions for it to work. I'll probably only have 100% sure to work repositories for emulators on this organization just to not get hopes up.

Makes sense, thanks for the response 😁
