### ISSUE TITLE
Emulation tab and any games I try to play instantly crash emu3ds

### ISSUE THREAD

**Issue by Harsh123G** [emuPlace/emuThreeDS#217]
I have checked most other issues with similar problems, but I can’t get it to work. I have enabled jit both in emuThreeDS and through altserver. I am running iOS 16.5.1 with security patch.

**Comment by Harsh123G** [comment]
Also I’m on an older iPad Pro 10.5 inch

**Comment by pantendo** [comment]
How do you enable JIT in AltServer? Did you pay for the beta version or use a third party software such as Jitterbug? Just curious because I can't get JIT to work.

**Comment by Harsh123G** [comment]
I am on windows 10 so I press on the system tray (the little up arrow next to the clock) and then I hover over altserver. If you do this right then when you hover over altserver you can see a few options. You should see the option “enable JIT”. Now connect your iOS device and then when you hover on “enable JIT”, you will see your device name. Now you have to open emuthreeds on your connected device and then hover over the device name and you should see the emuthreeds as an option to enable JIT.

**Comment by Harsh123G** [comment]
You can do this without the beta version

**Comment by nendnd** [comment]
This emulator is so stupid i recommend not playing it so you wont waste your fucking time in life

**Comment by WLHQ** [comment]
> This emulator is so stupid i recommend not playing it so you wont waste your fucking time in life

Hey I want to see you make one better then this one. If you can't then shut up & stop giving the developer shit. They have a life too & this emulator is still in its early stages & it's to be expected to have problems so cool your jets & stop with the hate.

**Comment by pantendo** [comment]
Thank you so much
