### ISSUE TITLE
Using a .cxi but it won't appear in library after adding to roms folder

### ISSUE THREAD

**Issue by NuclearNova26** [emuPlace/emuThreeDS#218]
"This emulator only supports the 4 main rom formats; .cci, .cia, .cxi and .3ds."

_Originally posted by @official-antique in https://github.com/emuPlace/emuThreeDS/issues/198#issuecomment-1619520978_

Does anyone happen to know of a reason why my game isn't appearing in the library on emuThreeDS?

**Comment by official-antique** [comment]
Hey @NuclearNova26, sorry just looked at the code and apparently I didn't add support for those yet: [LibraryManager.swift#L48](https://github.com/emuPlace/emuThreeDS/blob/swift-re-rework/emuThreeDS/Swift/Classes/LibraryManager.swift#L48), I'll get that done once I'm back working on it.

**Comment by NuclearNova26** [comment]
Oh that's good to hear, thanks so much!!

**Comment by woah047** [comment]
> "This emulator only supports the 4 main rom formats; .cci, .cia, .cxi and .3ds."
> 
> 
> 
> _Originally posted by @official-antique in https://github.com/emuPlace/emuThreeDS/issues/198#issuecomment-1619520978_
> 
> 
> 
> Does anyone happen to know of a reason why my game isn't appearing in the library on emuThreeDS?
> 
>             

I had the same problem I changed the .cxi to .3ds and it now works perfectly

**Comment by NuclearNova26** [comment]
Are you able to share how you converted your .cxi to a .3ds file? I tried to look for a way to do that but never found anything helpful

**Comment by woah047** [comment]
> Are you able to share how you converted your .cxi to a .3ds file? I tried to look for a way to do that but never found anything helpful

All I did was changed the end which app are you accessing the file from

**Comment by NuclearNova26** [comment]
Oh my gosh, I did not realize I could just change the end of the file to .3ds! That is such a simple fix, thanks so much!! I feel pretty dumb for not trying that to begin with lol. I just tried it and it does in fact work now
