### ISSUE TITLE
Game crashing after game needs the keyboard

### ISSUE THREAD

**Issue by JupiterJellies** [emuPlace/emuThreeDS#219]
I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!

**Comment by JupiterJellies** [comment]
> I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!

I am on iPhone 12 with iOS 16.5.1

**Comment by pantendo** [comment]
> I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!

Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:

1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).

2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.

3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)

You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.

**Comment by JTPVR2** [comment]
> > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> 
> 
> 
> Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> 
> 
> 
> 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> 
> 
> 
> 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> 
> 
> 
> 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> 
> 
> 
> You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.

Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?

**Comment by pantendo** [comment]
> > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> > 
> > 
> > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> > 
> > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> > 
> > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> 
> Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?

I'm not entirely sure, but I would say it's worth a try.

**Comment by JTPVR2** [comment]
> > > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> 
> > > 
> 
> > > 
> 
> > > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> 
> > > 
> 
> > > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> 
> > > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> 
> > > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> 
> > > 
> 
> > > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> 
> > 
> 
> > Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?
> 
> 
> 
> I'm not entirely sure, but I would say it's worth a try.

Ok, thanks for the info for both of us

**Comment by pantendo** [comment]
> > > > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> > 
> > 
> > > >
> > 
> > 
> > > > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> > 
> > 
> > > > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> > 
> > 
> > > > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> > 
> > 
> > > >
> > 
> > 
> > > > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> > 
> > 
> > > 
> > 
> > 
> > > Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?
> > 
> > 
> > I'm not entirely sure, but I would say it's worth a try.
> 
> Ok, thanks for the info for both of us

No worries!

**Comment by JTPVR2** [comment]
> > > > > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> 
> > > 
> 
> > > 
> 
> > > > > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> 
> > > 
> 
> > > 
> 
> > > > > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?
> 
> > > 
> 
> > > 
> 
> > > I'm not entirely sure, but I would say it's worth a try.
> 
> > 
> 
> > Ok, thanks for the info for both of us
> 
> 
> 
> No worries!

Hey, I tried your steps and I found out I need a 3DS to make keys, I looked up downloads for them and I got them. I put them inside of the sys file and I went to the preferences. When I got to the preferences stage, the download button won't work and on the side it says that I need keys. Please help

**Comment by JTPVR2** [comment]
> > > > > > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?
> > 
> > > > 
> > 
> > > > 
> > 
> > > > I'm not entirely sure, but I would say it's worth a try.
> > 
> > > 
> > 
> > > Ok, thanks for the info for both of us
> > 
> > 
> > 
> > No worries!
> 
> Hey, I tried your steps and I found out I need a 3DS to make keys, I looked up downloads for them and I got them. I put them inside of the sys file and I went to the preferences. When I got to the preferences stage, the download button won't work and on the side it says that I need keys. Please help

Nvm I fixed it lol

**Comment by pantendo** [comment]
> > > > > > > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > I'm not entirely sure, but I would say it's worth a try.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Ok, thanks for the info for both of us
> > > 
> > > 
> > > No worries!
> > 
> > 
> > Hey, I tried your steps and I found out I need a 3DS to make keys, I looked up downloads for them and I got them. I put them inside of the sys file and I went to the preferences. When I got to the preferences stage, the download button won't work and on the side it says that I need keys. Please help
> 
> Nvm I fixed it lol

Alright, good to hear. Did the game end up working?

**Comment by devybacon** [comment]
> > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> 
> Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> 
> 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> 
> You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.

pls make it more specific I don’t know what to do

**Comment by JTPVR2** [comment]
> > > > > > > > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > Sonic works the same way but it only crashes after the Sega part. Can I do the same for sonic and the lost world?
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > I'm not entirely sure, but I would say it's worth a try.
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > Ok, thanks for the info for both of us
> 
> > > > 
> 
> > > > 
> 
> > > > No worries!
> 
> > > 
> 
> > > 
> 
> > > Hey, I tried your steps and I found out I need a 3DS to make keys, I looked up downloads for them and I got them. I put them inside of the sys file and I went to the preferences. When I got to the preferences stage, the download button won't work and on the side it says that I need keys. Please help
> 
> > 
> 
> > Nvm I fixed it lol
> 
> 
> 
> Alright, good to hear. Did the game end up working?

Yes the game works now thanks to you

**Comment by JTPVR2** [comment]
> > > I'm trying to play Tomodachi Life but every time I try to name my island the game crashes. The same goes for Mii maker, every time I try to name my mii the game also crashes. Yes I tried enabling JIT, it don't work. Please help!
> 
> > 
> 
> > Hello! I had this same issue, but managed to fix it today. You're going to need the latest version of Citra on your PC/Mac. Here's what I did:
> 
> > 
> 
> > 1. Open your laptop and navigate to your Citra directory folder. From here, you want to insert your AES keys into the sysdata folder. You can learn how to obtain AES keys [here](https://citra-emu.org/wiki/aes-keys/).
> 
> > 2. Next, you want to open Citra preferences and select System. At the bottom, there will be a download section. Select your region, and New 3DS (make sure the region you select matches with the region of the Tomodachi Life ROM). Press download, and wait for a few moments before the download is complete.
> 
> > 3. Now, navigate to your Citra user directory and copy all of the files onto your EmuthreeDS folder on your iPhone. (You may use a file transfer platform such as Dropbox or Google Drive.)
> 
> > 
> 
> > You should now be able to play Tomodachi Life without it crashing at the island naming section. Please let me know if you have any problems.
> 
> 
> 
> pls make it more specific I don’t know what to do

Search for a shared 3DS system file and replace those files into the citra files on your computer. After that, go to the citra configurations and download the system. Before you download, enter your region and enter new 3DS. Then download the full system by pressing download. After you downloaded the system, transfer all of the citra files from your computer onto Google drive to your phone and all of those new files you got, replace the emuthreeds files with the new ones and your done.

**Comment by devybacon** [comment]
thanks bro I’m am a retard

**Comment by JTPVR2** [comment]
> thanks bro I’m am a retard

Nah bro your good lol

**Comment by devybacon** [comment]
> > thanks bro I’m am a retard
> 
> Nah bro your good lol

ok so maybe I’m still a retard cus like when I used a shared 3ds file system still experience crashed when on name island on tomodachi game 😞

**Comment by JTPVR2** [comment]
> > > thanks bro I’m am a retard
> 
> > 
> 
> > Nah bro your good lol
> 
> 
> 
> ok so maybe I’m still a retard cus like when I used a shared 3ds file system still experience crashed when on name island on tomodachi game 😞

Did you put the files into the citra files?

**Comment by devybacon** [comment]
> > > > thanks bro I’m am a retard
> > 
> > 
> > > 
> > 
> > 
> > > Nah bro your good lol
> > 
> > 
> > ok so maybe I’m still a retard cus like when I used a shared 3ds file system still experience crashed when on name island on tomodachi game 😞
> 
> Did you put the files into the citra files?

OHH SHIT I FORGOT

**Comment by devybacon** [comment]
I’ll do it when I get home

**Comment by JTPVR2** [comment]
> I’ll do it when I get home

Ok lol

**Comment by JTPVR2** [comment]
> > > > > thanks bro I’m am a retard
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Nah bro your good lol
> 
> > > 
> 
> > > 
> 
> > > ok so maybe I’m still a retard cus like when I used a shared 3ds file system still experience crashed when on name island on tomodachi game 😞
> 
> > 
> 
> > Did you put the files into the citra files?
> 
> 
> 
> OHH SHIT I FORGOT

💀

**Comment by JTPVR2** [comment]
Good luck

**Comment by devybacon** [comment]
thanks bro I will say something if I still get issues

**Comment by JTPVR2** [comment]
> thanks bro I will say something if I still get issues

Text me on my discord, it's JTPVR

**Comment by devybacon** [comment]
ok

**Comment by pantendo** [comment]
Congrats for getting your game working @JTPVR2

**Comment by devybacon** [comment]
ok so I couldn’t find a Europe one so I chose Australia cus it didn’t mention Europe and now it just has the same issue pls help

**Comment by devybacon** [comment]
ok so I thought that because I did Australia it didn’t work so I did America and it still has the same issue pls help me @JTPVR2

**Comment by JTPVR2** [comment]
> ok so I thought that because I did Australia it didn’t work so I did America and it still has the same issue pls help me @JTPVR2 

What is the region on the tomodachi life Rom? Figure out the Region you downloaded on the rom and put the same region on the download system page

**Comment by devybacon** [comment]
I got it of romsfun and it USA so I did USA and the downloaded it and it still crashing

**Comment by JTPVR2** [comment]
> also can u go on discord my user is cool1573

Let's talk from there.
I messaged you

**Comment by 833K3R** [comment]
@JTPVR2 accept me on discord

**Comment by 833K3R** [comment]
and do you copy from /roaming/citra or /local/citra

**Comment by 833K3R** [comment]
> > thanks bro I will say something if I still get issues
> 
> Text me on my discord, it's jtpvr

Accept my friend request, I still can't get this to work
