### ISSUE TITLE
the app closes when I click on emulation

### ISSUE THREAD

**Issue by gsoismes** [emuPlace/emuThreeDS#220]
I have no idea what it could be

**Comment by pantendo** [comment]
Hello, I know how to fix this issue. Go to the Files app on your phone, and navigate your .3ds ROM. Move it to the roms folder, which is located in your EmuthreeDS user directory. Now, when you open EmuthreeDS, your game should be on the left of the screen.

**Comment by Tahsan228** [comment]
got the rom in but i cant emulate it
