### ISSUE TITLE
Pokemon Rumble World

### ISSUE THREAD

**Issue by OOFB0I** [emuPlace/emuThreeDS#223]
So when I try to play the game it forces me to have a mii and I have the mii maker but the face doesn’t work and the keyboards crash my game so idfk what to do someone tell me how I can possibly fix this 
Edit: Oh I have an iPhone 12 on 16.5.1

**Comment by Harsh123G** [comment]
Check the issue named “game crashes after game needs keyboard”. It just below your issue so you should find it and I hope it helps you.

**Comment by OOFB0I** [comment]
Ah thank you. But what about the faces not appearing?
