### ISSUE TITLE
Please a place to talk !

### ISSUE THREAD

**Issue by DanylLeStyle** [emuPlace/emuThreeDS#229]
Any way i can find a discord or a telegram server ? Idk why the olders ones shutted down

**Comment by JTPVR2** [comment]
> Any way i can find a discord or a telegram server ? Idk why the olders ones shutted down

I'm not sure if there's a discord but there was one

**Comment by DanylLeStyle** [comment]
Maybe we should make our own emuThreeDS unofficial server

**Comment by DanylLeStyle** [comment]
> > Any way i can find a discord or a telegram server ? Idk why the olders ones shutted down
> 
> I'm not sure if there's a discord but there was one

Maybe we should create our own emuThreeDS unofficial server

**Comment by JTPVR2** [comment]
> > > Any way i can find a discord or a telegram server ? Idk why the olders ones shutted down
> > 
> > I'm not sure if there's a discord but there was one
> 
> Maybe we should create our own emuThreeDS unofficial server.. because it would be easier for us to get news and exchange about issues…

That's a good idea

**Comment by DanylLeStyle** [comment]
> > > > Any way i can find a discord or a telegram server ? Idk why the olders ones shutted down
> > > 
> > > I'm not sure if there's a discord but there was one
> > 
> > Maybe we should create our own emuThreeDS unofficial server.. because it would be easier for us to get news and exchange about issues…
> 
> That's a good idea
> 

By any chance do you know how to make discord servers ?

**Comment by Moonlumen** [comment]
the discord was shutdown since it was "set up improperly" and there were immature people according to the developer's tweet
if anyone is willing to make a new one, i could help moderate or set it up, i have nothing better to do

**Comment by Leakyhandle** [comment]
Someone already made a unofficial server here’s the link https://discord.gg/prHVtrgY2G
