### ISSUE TITLE
App crashes whenever i click on emulation tab or try to launch a game. 

### ISSUE THREAD

**Issue by TheBossomeDoge** [emuPlace/emuThreeDS#230]
The app crashes whenever i try to click the emulation tab or try to launch a game. I have an iphone 12 that is up to date. Not sure why this is happening. I side-loaded it with sideloady instead of altstore.

**Comment by DanylLeStyle** [comment]
> The app crashes whenever i try to click the emulation tab or try to launch a game. I have an iphone 12 that is up to date. Not sure why this is happening. I side-loaded it with sideloady instead of altstore. 

Do you have JIT enabled in settings ?

**Comment by noga-aviator** [comment]
Same here, and JIT is working in other apps
