### ISSUE TITLE
Tilt Feature

### ISSUE THREAD

**Issue by JTPVR2** [emuPlace/emuThreeDS#231]
Hello @official-antique, this is more than a question rather than a request but will there ever be a tilt feature in the emulator? If so then do you have the code planned for the next release?

**Comment by official-antique** [comment]
Hey @JTPVR2, right now the code you see on the swift-re-rework branch is the latest code available (minus some minor changes). I've not had done much more on this emulator as I've partially burnt myself out on it and have been working on several others; NES, PS1, PS2.

I've thought of adding tilt (gyro) controls and had a somewhat working version of my own but never released it for testing, once I'm more stable financially and have more time I'd like to get everything done for this emulator as there's much more to do.

> I'm 100% completing it, I don't plan on killing it off any time soon, for those seeing this and wondering.

**Comment by JTPVR2** [comment]
> Hey @JTPVR2, right now the code you see on the swift-re-rework branch is the latest code available (minus some minor changes). I've not had done much more on this emulator as I've partially burnt myself out on it and have been working on several others; NES, PS1, PS2.
> 
> 
> 
> I've thought of adding tilt (gyro) controls and had a somewhat working version of my own but never released it for testing, once I'm more stable financially and have more time I'd like to get everything done for this emulator as there's much more to do.
> 
> 
> 
> > I'm 100% completing it, I don't plan on killing it off any time soon, for those seeing this and wondering.

Thanks for the response. I just want to say that your emulator is very swell especially with the community dude. I also want to say good luck on everything that's going on lol.
