### ISSUE TITLE
Just Keeps Crashing whenever the game is going to start

### ISSUE THREAD

**Issue by devybacon** [emuPlace/emuThreeDS#232]
I try to run MiiTopia and Tomodachi Life however it didn’t work for some reason as it kept crashing me do I have to jailbreak my device as I’m using scarlet to download my apps

**Comment by stossy11** [comment]
What device?

**Comment by devybacon** [comment]
iPhone 14 normal version iOS 17.0 hehe so maybe it just doesn’t work on that version

**Comment by loyahdev** [comment]
> iPhone 14 normal version iOS 17.0 hehe so maybe it just doesn’t work on that version

Indeed it doesn’t I have the same problem.

**Comment by stossy11** [comment]
> iPhone 14 normal version iOS 17.0 hehe so maybe it just doesn’t work on that version

I'm on iOS 17 and it works but try this: make sure the JIT isn’t enabled and HLE is enabled and don't click emulation on the bottom click the game and it sould work if it doesn't show a screen recording

**Comment by devybacon** [comment]
I’m trying to use tomodachi life but it crashes on the name part so does mii topia so what do I do non mii games work fine

**Comment by JTPVR2** [comment]
> I’m trying to use tomodachi life but it crashes on the name part so does mii topia so what do I do non mii games work fine

I have a solution for you with this problem
