### ISSUE TITLE
App crashes on iOS 17 when clicking emulation and jit doesn’t change anything

### ISSUE THREAD

**Issue by loyahdev** [emuPlace/emuThreeDS#233]
@official-antique I got some problems in the app with iOS 17 I’m supposing it’s with that version but I hope this gets fixed soon. The app crashes when clicking on the emulation tab and file importing doesn’t work. Upon pressing the plus button nothing happens. I’ve tried enabling jit through Xcode which is currently the only way and the emulation tab loads but then in app crashes. Even with jit file import doesn’t work.

**Comment by official-antique** [comment]
Hey @loyahdev, the current emulation tab will only work when a game has been tapped (loaded), I believe the formats supported are `.3ds`, `.cxi` and `.cci` and those should be placed in `/roms`.

**Comment by loyahdev** [comment]
> Hey @loyahdev, the current emulation tab will only work when a game has been tapped (loaded), I believe the formats supported are `.3ds`, `.cxi` and `.cci` and those should be placed in `/roms`.

How can I load them when I click the plus to import nothing happens. No file browser nothing.

**Comment by official-antique** [comment]
The Files app will have an emuThreeDS folder under `On my [Device]` which will itself have a `roms` folder. I've fixed all of that in the latest version but it isn't publicly available yet.

**Comment by loyahdev** [comment]
> The Files app will have an emuThreeDS folder under `On my [Device]` which will itself have a `roms` folder. I've fixed all of that in the latest version but it isn't publicly available yet.

Gotcha thank you. Also why in portrait mode both screens are so squished. Last thing can you make it so both the dpad and joystick controls both show in portrait mode and not just landscape?

**Comment by loyahdev** [comment]
There’s also games like tomodachi life that just randomly crash

**Comment by official-antique** [comment]
Apologies for the late reply, yes and no it is a bug, right now there's no camera, keyboard or gyro controls among some other stuff so when those get accessed it will crash. My local version does partially fix the keyboard by hard-coding a string but it will need to present the keyboard.
