### ISSUE TITLE
Request: make buttons transparent when using a bluetooth controller

### ISSUE THREAD

**Issue by arynrosh** [emuPlace/emuThreeDS#239]
Just a suggestion but would like if the on screen buttons could be hidden when using external controllers!

**Comment by official-antique** [comment]
Hey @arynrosh, this exists in the newest version which should be coming out this week.

**Comment by arynrosh** [comment]
> Hey @arynrosh, this exists in the newest version which should be coming out this week.

sweet! looking forward to it ty :)
