### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by Pikachupikachup** [emuPlace/emuThreeDS#24]
I want to fork the actual emu or try to look on how you make it, but it looks like you make the code in a different place than this git. Could you show the source code for the actual emulator?

**Comment by official-antique** [comment]
Fixed in the second latest commit. Ensure you read the README.

**Comment by Pikachupikachup** [comment]
Thanks! I was wondering though if you could make a swift package, just so I can try playing around with code because I don’t have a Mac. :(
