### ISSUE TITLE
Just a question abt bmac

### ISSUE THREAD

**Issue by DanylLeStyle** [emuPlace/emuThreeDS#241]
If I pay 6€ to get access to the next releases of emuThreeDS, do I have to pay monthly or can I just pay 1 time to get access to all the upcoming releases forever ? I ask that cuz 6€/month is quite expensive on a larger scale like a year (72€) and I don't think I really want to invest this much on anything. Considering that citra is completely free and dolphin too. (Citra new releases were public since the first day)... ty for your answer guys :)

**Comment by official-antique** [comment]
Hey @DanylLeStyle, Buy Me A Coffee is just there to get early access and to support the development, usually after the BMAC version has been out for a week it'll be released for all completely free.

**Comment by DanylLeStyle** [comment]
> Hey @DanylLeStyle, Buy Me A Coffee is just there to get early access and to support the development, usually after the BMAC version has been out for a week it'll be released for all completely free.

Yeah but is it a one time payment or rather a subscription to keep getting early access of new releases

**Comment by official-antique** [comment]
It is a subscription but you can cancel directly after if you'd like and still have full access in the current versions
