### ISSUE TITLE
Testflight

### ISSUE THREAD

**Issue by Pikachupikachup** [emuPlace/emuThreeDS#243]
I asked near April-May about when the TestFlight version will come out. I understand you may not have enough money to get your software on there, but I wanted to know how close you are to releasing it there.

**Comment by EBmang101** [comment]
I don't think that's possible? It's Apple you know? :)

**Comment by official-antique** [comment]
@Pikachupikachup sorry for the delay, I did want to put the emulator on TestFlight as it'd make access very easy but the 🥚 emulator got banned themselves changing my mind

**Comment by Pikachupikachup** [comment]
Oh. Man, I using a school iPad so I can’t get altstore or troll store, but I can get TestFlight. I understand tho.
