### ISSUE TITLE
Stop emulation?

### ISSUE THREAD

**Issue by MichaelMKenny** [emuPlace/emuThreeDS#245]
I've compiled the "swift-re-rework" branch, and the emulator runs great, running through the debugger to get JIT. But I don't know how to stop a game (go back to Library). I've added my own stop button that always appears (even when the controller is connected), but I'm not sure what to call to stop emuation. 

I've tried:
`core.RequestShutdown();` and `core.Shutdown();`
But RequestShutdown doesn't seem to do anything, and Shutdown seems to crash.
I've also tried just simply dismissing the EmulationViewController, but when launch a game again it crashes, so I tried deallocing some of properties, but with no luck. I also tried setting `_isRunning = false;`, as that seem to help stop problems in the while loop.

But really I've only spent the past hour or so in this code base, and don't really know what I'm doing. So I was wondering if you plan to add a stop emulation button, gamepad shortcut, or keyboard shortcut? Maybe you've already implemented this, just not pushed it to GitHub?

Anyway, this emulator is very impressive, and I just want to say thank you for all your hard work. I love passion projects like these :)

**Comment by official-antique** [comment]
Hey @MichaelMKenny, right now there's no way to pause emulation other than to background the app with foregrounding resuming emulation and no way at all to stop it yet. I've done a bit of testing with porting Android's `NativeLibrary_StopEmulation()` but it doesn't appear to work very well when running a new game.

**Comment by MichaelMKenny** [comment]
@official-antique Ah, thanks for letting me know and for the quick reply :)
