### ISSUE TITLE
What's Going on?

### ISSUE THREAD

**Issue by JTPVR2** [emuPlace/emuThreeDS#248]
Hey @official-antique so I downloaded the new release of EmuThreeDS and I see that it says authenticate. I checked the coffee website and I need to pay. Did I download the wrong version or something because I thought we could use this for free..

**Comment by WayneDX** [comment]
> Hey @JTPVR2, right now the latest versions will be for BMAC members only, with the release of a new version the older one will unlock automatically. There is also an issue with the latest where it may fail authenticating due to the returned data which I'll fix tomorrow.

Hey also I can not play with this version ? I must pay for this ?

**Comment by JTPVR2** [comment]
> > Hey @JTPVR2, right now the latest versions will be for BMAC members only, with the release of a new version the older one will unlock automatically. There is also an issue with the latest where it may fail authenticating due to the returned data which I'll fix tomorrow.
> 
> 
> 
> Hey also I can not play with this version ? I must pay for this ? 

Sadly yes untill it becomes free again

**Comment by WayneDX** [comment]
> > > Hey @JTPVR2, right now the latest versions will be for BMAC members only, with the release of a new version the older one will unlock automatically. There is also an issue with the latest where it may fail authenticating due to the returned data which I'll fix tomorrow.
> > 
> > 
> > Hey also I can not play with this version ? I must pay for this ?
> 
> Sadly yes untill it becomes free again

When will it be free ???

**Comment by WayneDX** [comment]
> > > Hey @JTPVR2, right now the latest versions will be for BMAC members only, with the release of a new version the older one will unlock automatically. There is also an issue with the latest where it may fail authenticating due to the returned data which I'll fix tomorrow.
> > 
> > 
> > Hey also I can not play with this version ? I must pay for this ?
> 
> Sadly yes untill it becomes free again

And why is my game so laggy??

**Comment by JTPVR2** [comment]
> > > > Hey @JTPVR2, right now the latest versions will be for BMAC members only, with the release of a new version the older one will unlock automatically. There is also an issue with the latest where it may fail authenticating due to the returned data which I'll fix tomorrow.
> 
> > > 
> 
> > > 
> 
> > > Hey also I can not play with this version ? I must pay for this ?
> 
> > 
> 
> > Sadly yes untill it becomes free again
> 
> 
> 
> And why is my game so laggy??

Enable JIT. Search for how to.
