### ISSUE TITLE
Slow game

### ISSUE THREAD

**Issue by Elenaa213** [emuPlace/emuThreeDS#251]
When i start a game its just slow ?? There’s a solution?

**Comment by efa90930backup** [comment]
Disable JIT, open a game, enable JIT, should fix your lag

**Comment by Elenaa213** [comment]
How can i enable JIT when the game is open?

**Comment by efa90930backup** [comment]
go to emuplace.app/emulators/emuthreeds, lag is kind of fixed in newer versions and the GitHub isn’t updating with new versions
