### ISSUE TITLE
emuThreeDS.v1.0.6.5.6 eror

### ISSUE THREAD

**Issue by ZabiTillT** [emuPlace/emuThreeDS#253]
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(697): _assert(): false

**Comment by official-antique** [comment]
Hey @ZabiTillT, this is a known issue with both Alt and SideStore likely caused by Xcode 15 (it seems to have started after the change from 14).

Depending on your system, you may want to try Apple Configurator (macOS) or esign as those are known to work.

**Comment by Kdog88** [comment]
Can i get a link to the official esign website? I wanna make sure that i download the official one and not a malicious one.

**Comment by Kdog88** [comment]
Still looking for the official link to ensign....if you could please link me to the official website so that I can sign the latest version so that i can play games in the emulator

**Comment by JTPVR2** [comment]
> Still looking for the official link to ensign....if you could please link me to the official website so that I can sign the latest version so that i can play games in the emulator 

I got a link for you

**Comment by JTPVR2** [comment]
> Still looking for the official link to ensign....if you could please link me to the official website so that I can sign the latest version so that i can play games in the emulator 

You can try using scarlet. I used it and it works perfectly. Here's the link. https://usescarlet.com scroll all the way down and press install. After that, download direct download and install the profile.

**Comment by JTPVR2** [comment]
> > Still looking for the official link to ensign....if you could please link me to the official website so that I can sign the latest version so that i can play games in the emulator 
> 
> You can try using scarlet. I used it and it works perfectly. Here's the link. https://usescarlet.com scroll all the way down and press install. After that, download direct download and install the profile.

And scarlet can expire on your phone, to fix that, look up how to fix blacklist on scarlet in safari

**Comment by JTPVR2** [comment]
> > > Still looking for the official link to ensign....if you could please link me to the official website so that I can sign the latest version so that i can play games in the emulator 
> > 
> > You can try using scarlet. I used it and it works perfectly. Here's the link. https://usescarlet.com scroll all the way down and press install. After that, download direct download and install the profile.
> 
> And scarlet can expire on your phone, to fix that, look up how to fix blacklist on scarlet in safari

Here's the link https://docs.usescarlet.com/scarlet/anti-revoke

**Comment by Kdog88** [comment]
Does that scarlet blacklist link prevent sideloaded app from also expiring too? Or just the scarlet app?

**Comment by JTPVR2** [comment]
> Does that scarlet blacklist link prevent sideloaded app from also expiring too? Or just the scarlet app? @JTPVR2 

Well scarlet itself prevents expiration

**Comment by JTPVR2** [comment]
> Does that scarlet blacklist link prevent sideloaded app from also expiring too? Or just the scarlet app? @JTPVR2 

Apps last for a year

**Comment by JTPVR2** [comment]
> > Does that scarlet blacklist link prevent sideloaded app from also expiring too? Or just the scarlet app? @JTPVR2 
> 
> Apps last for a year

For free

**Comment by JTPVR2** [comment]
> Does that scarlet blacklist link prevent sideloaded app from also expiring too? Or just the scarlet app? @JTPVR2 

Also turn on the vpn with the blacklist file after you sideloaded all of your apps you wanted to sideload.

**Comment by JTPVR2** [comment]
> Does that scarlet blacklist link prevent sideloaded app from also expiring too? Or just the scarlet app? @JTPVR2 

If you have anymore questions, text me on my discord jtpvr

**Comment by Kdog88** [comment]
@JTPVR2 cant dm you on discord bc how discord dms works...does the pc version require you to refresh the sideloaded apps? I currently use altstore for sideloading but you have to refresh the sideloaded apps no less than once per week....if scarlet on pc allows you to not have to refresh the sideloaded apps, then id gladly use it in favor of sideloading apps

**Comment by JTPVR2** [comment]
> @JTPVR2 cant dm you on discord bc how discord dms works...does the pc version require you to refresh the sideloaded apps? I currently use altstore for sideloading but you have to refresh the sideloaded apps no less than once per week....if scarlet on pc allows you to not have to refresh the sideloaded apps, then id gladly use it in favor of sideloading apps 

No need to refresh on all versions. I recommend the direct version because you can sideload anywhere at anytime standalone but your choice.

**Comment by namquang93** [comment]
I got this error too. Anyone has a solution for this?
