### ISSUE TITLE
motion controls not working

### ISSUE THREAD

**Issue by canbarlas** [emuPlace/emuThreeDS#256]
I'm playing kirby. I can't tilt in the game, how do I do it?  motion controls not working

**Comment by JTPVR2** [comment]
> I'm playing kirby. I can't tilt in the game, how do I do it?  motion controls not working

Sorry bro, the feature isn't out

**Comment by JTPVR2** [comment]
> I'm playing kirby. I can't tilt in the game, how do I do it?  motion controls not working

Antique planned it and tested it and it didn't work out well so he stopped using it

**Comment by canbarlas** [comment]
Thanks a lot

**Comment by JTPVR2** [comment]
> Thanks a lot

Yeah sorry, I wish they had this feature
