### ISSUE TITLE
It’s getting there but…

### ISSUE THREAD

**Issue by justaniceguy100** [emuPlace/emuThreeDS#257]
EmuThreeDS is great and your doing great but I have three issues and I know you’ll resolve these at some point but just so you know: Save states don’t work- this is pretty big deal, I mean ld like to close a game knowing I can resume it at any time portrait and landscape orientation cannot be changed regardless of the orientation you select in settings- in older versions of emuThreeDS you can change the orientation of the top and bottom screen, in current version that isn’t present. Lastly I’d like to be able to stop emulation instead of having to close the app. Since I have to re enable jit
![C25DA6EF-B4B0-481A-BCD6-B3855715B28B](https://github.com/emuPlace/emuThreeDS/assets/127481809/00645867-8de7-4d22-9fb6-30bef9fc0af4)

**Comment by orlandu97** [comment]
No luck with enabling Jit in latest update?

**Comment by justaniceguy100** [comment]
It works but emuThreeDS still crashes on some games if he made a compatibility list that'd be nice

**Comment by efa90930backup** [comment]
Disable JIT, open a game, then enable JIT. It will open the game and make it so you won’t have lag like if you disabled JIT

**Comment by justaniceguy100** [comment]
Well I mean Mario kart 7 still crashes

**Comment by orlandu97** [comment]
> Disable JIT, open a game, then enable JIT. It will open the game and make it so you won’t have lag like if you disabled JIT

how do u Enable JIT after Running a game? in the latest update there's no option to "Edit settings" after a game is run.

**Comment by justaniceguy100** [comment]
EmuThreeDS is super laggy

**Comment by JTPVR2** [comment]
> EmuThreeDS is super laggy 

Enable JIT

**Comment by WLHQ** [comment]
How do we enable JIT on non Jailbroken devices without crashing when launching a game?

**Comment by JTPVR2** [comment]
> How do we enable JIT on non Jailbroken devices without crashing when launching a game?

Alt store, JitStreamer, jitterbug

**Comment by JTPVR2** [comment]
> How do we enable JIT on non Jailbroken devices without crashing when launching a game?

Look them up
