### ISSUE TITLE
When can we support ios14?

### ISSUE THREAD

**Issue by Dekrkdk** [emuPlace/emuThreeDS#26]
My ipad is ios 14.7, and I just want to keep my trollstore, so I can’t update my ipad system.

**Comment by Wurseyan** [comment]
> My ipad is ios 14.7, and I just want to keep my trollstore, so I can’t update my ipad system.

Update your iPad to iPadOS 15.4.1 (trollstore compatible) there is a lot of videos on YouTube about that and note that ios 15.4.1 is jailbreak compatible if you have A12 or higher

Jailbreak 15.4.1 : https://ellekit.space/dopamine/

Trollstore : https://github.com/opa334/TrollStore

**Comment by yes67** [comment]
> > My ipad is ios 14.7, and I just want to keep my trollstore, so I can’t update my ipad system.
> 
> Update your iPad to iPadOS 15.4.1 (trollstore compatible) there is a lot of videos on YouTube about that and note that ios 15.4.1 is jailbreak compatible if you have A12 or higher
> 
> Jailbreak 15.4.1 : https://ellekit.space/dopamine/
> 
> Trollstore : https://github.com/opa334/TrollStore

You can’t update to 15.4.1

**Comment by emuladoressyt** [comment]
Hello, how would it be possible one day to work on A10Fusion and A11 Apple iPhone 7 Plus and 8 Plus

**Comment by official-antique** [comment]
@Dekrkdk, iOS 14 support isn't planed currently but the only issue is the GCVirtualController (will require a custom made view).

@emuladoressyt, It's very unlikely that anything lower than an iPhone XR/XS will be able to run the emulator and this won't change as the memory and processing power of those devices is too low.
