### ISSUE TITLE
Screen is stretched out on iPads

### ISSUE THREAD

**Issue by efa90930backup** [emuPlace/emuThreeDS#260]
![IMG_1818](https://github.com/emuPlace/emuThreeDS/assets/141432503/6d4c1be7-d9ad-46d2-aa0c-bd55ca36cce2)

**Comment by official-antique** [comment]
Hey @efa90930backup, this may be due to the layout option selected which I believe doesn't get changed with the setting change right now, I'll try to fix that tomorrow and get an update out
