### ISSUE TITLE
Will the emulator work for Altstore?

### ISSUE THREAD

**Issue by eramo607** [emuPlace/emuThreeDS#27]
Will this emulator work for Altstore, or will it be only used for Trollstore? Because I’m not sure if it will be considering I’ve been seeing a bunch of comments mentioning Trollstore.

It may also be fair to ask if this emulator can work on anything else supporting them?

**Comment by TH3-I** [comment]
Can confirm, it works on AltStore. That's how I installed it.

**Comment by eramo607** [comment]
> Can confirm, it works on AltStore. That's how I installed it.

Okay thank you.
