### ISSUE TITLE
部分游戏闪退

### ISSUE THREAD

**Issue by gonjudaren** [emuPlace/emuThreeDS#275]
目前测试口袋妖怪始源蓝宝石完美运行，开JIT之后A13设备偶尔会闪退，口袋妖怪XY没有BGM，其他没有问题，究极日月进入游戏界面后20秒闪退 。。。。

**Comment by official-antique** [comment]
口袋妖怪游戏确实有问题，音乐是由于新的音频代码造成的，可能很快就会修复，但速度快是好事

**Comment by 3074741300** [comment]
@official-antique 3d马里奥大陆会崩溃

**Comment by official-antique** [comment]
我认为马里奥崩溃是因为没有键盘

**Comment by a352237292** [comment]
老板，什么时候考虑修复怪物猎人系列崩溃问题，在1.0.5.x版本中是正常的，进入1.0.6.x版本后开始出现崩溃，这是我最喜欢的游戏系列，并且已捐助您的bmac，谢谢

**Comment by gonjudaren** [comment]
新超级马里奥兄弟2 闪退

**Comment by gonjudaren** [comment]
银河战士：萨姆斯归来  游戏可以导入 进入模拟器头像显示乱码  无法打开游戏

**Comment by gonjudaren** [comment]
星之卡比机械星球 无法打开

**Comment by gonjudaren** [comment]
逆转裁判4

**Comment by gonjudaren** [comment]
无法打开

**Comment by a352237262** [comment]
> 逆转裁判4

13pro max (ios16.6) 可以正常运行，你是什么设备和ios版本？

**Comment by gonjudaren** [comment]
> > 逆转裁判4
> 
> 13pro max (ios16.6) 可以正常运行，你是什么设备和ios版本？

苹果12 系统版本16

**Comment by gonjudaren** [comment]
模拟器版本 1.0.6.5.6

**Comment by gonjudaren** [comment]
然后就是塞尔达卡顿延迟  希望尽快修复  详情请看我的哔哩哔哩 主页【iOS 3ds模拟器测试 塞尔达 卡顿延迟-哔哩哔哩】 https://b23.tv/aXMSA11
