### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by Bl3477ev** [emuPlace/emuThreeDS#28]
I don’t know how to download

**Comment by official-antique** [comment]
You can find downloads by going to [/releases](https://github.com/emuplace/emuthreeds/releases). You'll need to sideload the app to your device to use it.

**Comment by Bl3477ev** [comment]
Do i use altstore?

**Comment by eramo607** [comment]
> Do i use altstore?

I opened up another issue asking this same question. It’s possible to open it up on AltStore.

**Comment by JIMMY523elcrak** [comment]
I don’t know how to download

**Comment by JIMMY523elcrak** [comment]
Sorry i download now
