### ISSUE TITLE
Love the app; slight issue regarding sound

### ISSUE THREAD

**Issue by nishupad** [emuPlace/emuThreeDS#280]
First of all, to the person who created this, THANK YOU SO MUCH! I'm able to relive my childhood thanks to this amazing emulator; it almost feels like my broken 3DS came back to life again! The only slight issue I wanted to point out is that I'm unable to hear any background music even though I'm able to hear the sound effects (e.g. footsteps, button noises, etc.) when I'm playing Pokemon X. I'm running EmuThreeDS version 1.0.6.5.6 on my iPhone 12 Pro (iOS 16.6). Does anyone know what the cause of this issue is? Am I the only one with this issue or are there others? Please let me know what's going on and if there's any way I can fix this.

**Comment by pythonr0ck** [comment]
Explanation from: https://github.com/emuPlace/emuThreeDS/issues/33
The music files in Pokémon X/Y are in AAC. Citra already solved this by implementing an https://github.com/citra-emu/citra/pull/4508. All you can do right now is to wait until Antique updates emuThreeDS.
