### ISSUE TITLE
How to remove games from the app?

### ISSUE THREAD

**Issue by TheO1dF** [emuPlace/emuThreeDS#287]
I've been looking for a long time and I don't know how to remove the game from within the game. Or do I have to uninstall the entire app to completely delete the games in the app?

If not, hope to add this feature in the next version.

**Comment by 1-Python** [comment]
If you imported the 3DS rom as a .3DS file, then you can delete those .3DS roms in the emuThreeDS rom directory. To find it, go to the files app, go to On my iPhone (or On my iPad) > emuThreeDS > roms. Here you can delete the games. Hope I helped!

**Comment by TheO1dF** [comment]
.cci files can be deleted externally, but .cia files still exist after external deletion. I am wondering whether an app that can only be read and cannot be deleted internally is considered a lack of functionality?

**Comment by pythonr0ck** [comment]
Yeah, it would be. I hope antique will add it in the next update.
