### ISSUE TITLE
+ Button bug

### ISSUE THREAD

**Issue by sprit9244** [emuPlace/emuThreeDS#288]
When i hit the + button, nothing happens, how do i add my games then?

**Comment by pythonr0ck** [comment]
Go to the files app, go to On my iPhone (or On my iPad) > emuThreeDS > roms. Here you can import the games. The games you import here have to be .3ds, .cci, or .cxi. Importing .cia files requires 1.0.6.5.0 and up. Hope I helped!

**Comment by cccRaim** [comment]
> 转到文件应用程序，转到在我的 iPhone 上（或在我的 iPad 上）> emuThreeDS > rom。在这里您可以导入游戏。您在此处导入的游戏必须是 .3ds、.cci 或 .cxi。导入 .cia 文件需要 1.0.6.5.0 及更高版本。希望我有帮助！

I use 1.0.7.1, but when I import cia file, "Convert CIA" and "Import CIAs" not works.
The 1.0.7.1 is from https://emuplace.app/altstore.json

**Comment by pythonr0ck** [comment]
I have no idea why it isn’t working for you as it does work for me. The only thing I can think of is to make sure you’re on the latest version of emuThreeDS, which is 1.0.7.1 (2) (not 1.0.7.1 (1)) as of now. I think you should open a new issue.
