### ISSUE TITLE
Update Documentation!

### ISSUE THREAD

**Issue by pythonr0ck** [emuPlace/emuThreeDS#290]
Many links in this project are outdated, so here is a small list of things you need to update. You are probably aware of this but it’s been too long since these been updated, so here we go.

**BMAC**
Location: Sponsor this project section and in README.md in Support section.
Description: Redirects to https://buymeacoffee.com/antiquecodes instead of https://www.buymeacoffee.com/antique

**README.md**
Location: in project files
Description: BUILDING.md and CHANGELOG.md both redirect to the swift-re-rework branch instead of the main branch.

**Releases**
Location: Releases
Description: 1.0.7.1’s description in https://emuplace.app/emulators/emuthreeds/ doesn’t sound like it can only be used for this week. Is it limited in any way, or is the releases tab in GitHub just outdated?

**CHANGELOG.md**
Location: in project files
Description: 1.0.7.1 (1) and 1.0.7.1 (2) are out already.

**Comment by efa90930backup** [comment]
The release tab in GitHub is outdated, and I don’t think updates will be halted in the website either.
