### ISSUE TITLE
Installed the 3ds emulator... but something is wrong. help.

### ISSUE THREAD

**Issue by Ayoendit** [emuPlace/emuThreeDS#31]
I have put rom files in the /roms folder in the files app but when i got back, nothing really showed up. Is there a way to fix this?

**Comment by official-antique** [comment]
Hey @Ayoendit, could you send a screenshot of your roms folder?

**Comment by TalenzTrix6** [comment]
Close the app but don’t delete it, then they will be there also the roms have to be in .3ds format.

**Comment by Ayoendit** [comment]
> Hey @Ayoendit, could you send a screenshot of your roms folder?

![IMG_0590](https://user-images.githubusercontent.com/120703280/235330245-98952683-634c-47fd-ae7c-670f98d1a458.png)
![IMG_0589](https://user-images.githubusercontent.com/120703280/235330246-a8706523-7181-4f07-a7be-366c66961262.jpeg)

**Comment by SleepingSnakezzz** [comment]
"(eshop)". I assume that means "encrypted". Which would explain why it doesn't show up in the app. Dump decrypted:

[**Dumping Game Cartridges**](https://citra-emu.org/wiki/dumping-game-cartridges)
[**Dumping Installed Titles**](https://citra-emu.org/wiki/dumping-installed-titles)
[**Dumping Updates and DLC**](https://citra-emu.org/wiki/dumping-updates-and-dlcs/)

**Comment by Ayoendit** [comment]
> "(eshop)". I assume that means "encrypted". Which would explain why it doesn't show up in the app. Dump decrypted:
> 
> [**Dumping Game Cartridges**](https://citra-emu.org/wiki/dumping-game-cartridges) [**Dumping Installed Titles**](https://citra-emu.org/wiki/dumping-installed-titles) [**Dumping Updates and DLC**](https://citra-emu.org/wiki/dumping-updates-and-dlcs/)

Can you please help me
how do i make it decrypted?

do i use .cia?

**Comment by Ayoendit** [comment]
im going to close the issue now. @SleepingSnakezzz was right about the files. thank you man.
And thank you @official-antique .
