### ISSUE TITLE
Release updated binary?

### ISSUE THREAD

**Issue by ant-7802** [emuPlace/emuThreeDS#32]
I would like to play this properly using touch screen, which seems to be in the new update (I don’t have a Mac)

**Comment by subwxxfer** [comment]
U don't need to have a Mac for installing EmuThreeDS, if u have an Windows PC/Laptop u can use SideStore;)

**Comment by ant-7802** [comment]
> U don't need to have a Mac for installing EmuThreeDS, if u have an Windows PC/Laptop u can use SideStore;)

I meant.. compiling..
