### ISSUE TITLE
Will there be an HLE AAC decoder update to make sounds in Pokemon X/Y work?

### ISSUE THREAD

**Issue by charIesdoritos07** [emuPlace/emuThreeDS#33]
Pokemon X/Y runs perfectly but it has no BGM (music files are in AAC). This issue was resolved by Citra via implementing an [HLE AAC to FFMPEG decoder](https://github.com/citra-emu/citra/pull/4508). Would this feature be added in the future?

**Comment by ConstantineVac** [comment]
Yes that would be great, It´s very much needed 👀
