### ISSUE TITLE
Use Citra vulkan backend instead of OpenGL conversion

### ISSUE THREAD

**Issue by Wurseyan** [emuPlace/emuThreeDS#38]
Since OpenGL is not supported on apple devices, an conversion was needed but citra team just announced that citra will support natively vulkan backend in the next builds soon so it will be a good idea to remove the OpenGL conversation layer to just convert vulkan -> metal.

"Surprise Announcement" in https://citra-emu.org/entry/citra-progress-report-2023-q1/#surprise-announcement

**Comment by duckfromdiscord** [comment]
That's what we're doing 🙂

**Comment by duckfromdiscord** [comment]
emuThreeDS is using moltenvk vulkan

**Comment by official-antique** [comment]
I've just recently converted all GLSL shaders to SPIR-V, just have to connect them up.

I've also removed all OpenGL code minus the shader conversion code which will be removed when the above is done.

**Comment by Wurseyan** [comment]
Ok thanks

**Comment by official-antique** [comment]
Closing as already completed.
