### ISSUE TITLE
Mii?

### ISSUE THREAD

**Issue by PatchedHole** [emuPlace/emuThreeDS#40]
i opened 3D Land and it says i need to create one

**Comment by PatchedHole** [comment]
> i opened 3D Land and it says i need to create one

i press the ok button and then a crash

**Comment by AjayShanker-geek** [comment]
Hi, it would be great to help the dev by sharing your .log ips file.

### Steps
You can get your ips file from `Settings` > `Privacy & Security` > `Analytics & Improvements` > `Analytics Data` > `emuThreeDS-[latest-by-date].ips`

**Comment by PatchedHole** [comment]
> wait nvm i saw the thing

sorry
