### ISSUE TITLE
I need help pls.

### ISSUE THREAD

**Issue by Ayoendit** [emuPlace/emuThreeDS#41]
My ipad 8 gen runned the application but when i played a game, there is no sound.
Or, all rom files i tried on have no sounds.
My settings:
Silent mode: Off
Volume:100%
what do i do to fix this?

**Comment by official-antique** [comment]
Hey, right now I'm not too sure what's causing the audio issue. I'll try look into it tomorrow if I've got time.

**Comment by Ayoendit** [comment]
> Hey, right now I'm not too sure what's causing the audio issue. I'll try look into it tomorrow if I've got time.

Ok thank you man

**Comment by Zoobmaball** [comment]
I share the same issue

**Comment by subwxxfer** [comment]
> > Hey, right now I'm not too sure what's causing the audio issue. I'll try look into it tomorrow if I've got time.
> 
> 
> 
> Ok thank you man

I think it's caused by Bluetooth Headphones, try again without them.

**Comment by Ayoendit** [comment]
Hmmm...
This Bug is a bit long...
And i dont think its gonna be fixed :/

**Comment by official-antique** [comment]
I'm currently being trialed for a job and haven't had time to work on this due to that, once I'm aware of the outcome I'll be able to allocate some time around the result.

**Comment by JTPVR2** [comment]
Audio seems fine to me, what version is it?
