### ISSUE TITLE
How do we insert a Mii during a game

### ISSUE THREAD

**Issue by PatchedHole** [emuPlace/emuThreeDS#43]
i dont understand how it works

**Comment by c22dev** [comment]
Have you imported your NAND ?
Use threeSD for this : https://github.com/zhaowenlan1779/threeSD/wiki/Quickstart-Guide

**Comment by PatchedHole** [comment]
> Have you imported your NAND ?
> 
> Use threeSD for this : https://github.com/zhaowenlan1779/threeSD/wiki/Quickstart-Guide

oh ok
