### ISSUE TITLE
games not appearing on list

### ISSUE THREAD

**Issue by DzXAnt22** [emuPlace/emuThreeDS#45]
Games (.cia) are not showing up on the list. They are placed in the right location. 

additional information:
emuThreeDS 1.0.5.1
iPhone 12 Pro Max
iOS 16.4
Installed using AltStore

**Comment by PatchedHole** [comment]
i think only .3ds works

**Comment by DzXAnt22** [comment]
yup, got it to work. Accidentally used an encrypted rom.
