### ISSUE TITLE
No folder on ipad air 5

### ISSUE THREAD

**Issue by katsutonn** [emuPlace/emuThreeDS#48]
Redownloaded it 3 times on my ipad air 5th gen and emuthreeDS folder is not appearing but the folder is on my iphone 11 first time I downloaded it

**Comment by furryalt** [comment]
Have you tried using the file manager, selecting an item, clicking on move and seeing if there is an EmuThreeDS folder. Same thing happened to me, but moving something into that folder made it appear.
