### ISSUE TITLE
This is not an issue, its a queastion. pls answer ❤️

### ISSUE THREAD

**Issue by Ayoendit** [emuPlace/emuThreeDS#5]
Hi creator, so im wondering if this nice 3ds emulator
Will be just on safari and does not need to download it.

**Comment by deformedRat** [comment]
The emulator will need to be downloaded to use

**Comment by subwxxfer** [comment]
U will need to download the emulator when it's finished, I recommend SideStore, it's an app signer, sideloader, jit enabler and app refresher, it can also refresh itself so it doesn't get revoked, u only need to be connected to Wifi or an Hotspot to do these things, u also need an pc/laptop once to set up, then not anymore, and the best is, u can use SideStore on almost every iOS version!
I am currently on iOS 16.4 and everything works fine!

Here is an YouTube tutorial how to set it up: https://youtu.be/6i2QL-09zpc

And btw, if u wanna play DS games on a Web App then use https://ds.44670.org/
Just simply add the site to the Homescreen!😁

**Comment by Ayoendit** [comment]
yes, i meant actually if the 3ds port is supporting "web app"

**Comment by official-antique** [comment]
Hey @Ayoendit, I'm not sure it's possible to run it in a web app as it's C++ and requires a fair amount of dependencies. Safari also has limitations with what it can run; see the DS web app for performance, etc.

**Comment by Ayoendit** [comment]
@official-antique The Ds app runs pretty well ig.
i got 60 frames

**Comment by moyaimoment** [comment]
It isn’t possible for the 3DS to be a Web Emulator, it’s to powerful for it.
