### ISSUE TITLE
Is there a discord?

### ISSUE THREAD

**Issue by Flixington** [emuPlace/emuThreeDS#56]
If there isn't a discord for this I'd be happy to set one up for you and then transfer ownership as a way of helping

**Comment by deformedRat** [comment]
There is a discord server, here's [the link](https://discord.com/invite/cB4d6tg5G2) 👍

**Comment by Flixington** [comment]
> There is a discord server, [here's the link](https://discord.com/invite/cB4d6tg5G2) 👍

Thanks!
