### ISSUE TITLE
roms not loading, ios 16.5 beta

### ISSUE THREAD

**Issue by arynrosh** [emuPlace/emuThreeDS#58]
i already have pokemon y rom in the folder but when i open the app, its a black screen and then no rom...what to do???

a suggestion: an option to load CID files manually...similar to loading roms on Delta or Retroarch
![IMG_0816](https://github.com/emuPlace/emuThreeDS/assets/133498471/41cc9368-dfe1-4ad2-a8fc-97a1959ebfb2)
![IMG_0817](https://github.com/emuPlace/emuThreeDS/assets/133498471/c0ede84f-37c4-4328-a621-ab982e38c327)
![IMG_0818](https://github.com/emuPlace/emuThreeDS/assets/133498471/d2c17dd8-4f89-4e43-8054-bab88bc4200b)

**Comment by ant-7802** [comment]
3ds files

**Comment by PatchedHole** [comment]
i'd suggest going to https://www.blueroms.ws/

**Comment by Quynhnoob** [comment]
> 3ds files

I put 3ds file into roms folder but nth happened like him (jus![image](https://github.com/emuPlace/emuThreeDS/assets/80960284/31a07201-3a00-4a07-8528-b7d9476105c4)t black screen). What should i do ?

**Comment by Pikachupikachup** [comment]
Maybe you need to un-compress it?

**Comment by Quynhnoob** [comment]
> Maybe you need to un-compress it?

I did :<![image](https://github.com/emuPlace/emuThreeDS/assets/80960284/d81ba5d3-670c-4c8e-82e8-fbf3f704b59c)

**Comment by Pikachupikachup** [comment]
No I mean someone else had this same problem, it was something about not being in the right format… I don’t remember. Maybe look thru the closed issues for the one I’m mentioning?

**Comment by official-antique** [comment]
Closing this as you've been provided with help however, have also shown proof of piracy.
