### ISSUE TITLE
I want a virtual buttons 

### ISSUE THREAD

**Issue by JIMMY523elcrak** [emuPlace/emuThreeDS#60]
I want a virtual buttons  AND virtual Jostick please

**Comment by JIMMY523elcrak** [comment]
When i get The buttons The game stops

**Comment by JIMMY523elcrak** [comment]
Please fix that

**Comment by PatchedHole** [comment]
im pretty sure they're doing that already

**Comment by JIMMY523elcrak** [comment]
Maybe

**Comment by ant-7802** [comment]
Virtual Controller Support

Please note, touch and virtual (on-screen) controller support are different things with touch referring to the lower screen.

Virtual (on-screen) controller support seems to be broken in v1.0.5.1. This will be fixed in v1.0.6.

**Comment by JIMMY523elcrak** [comment]
Ok thanks

**Comment by JIMMY523elcrak** [comment]
Update ? The emulador
