### ISSUE TITLE
Keybord name not appear 

### ISSUE THREAD

**Issue by Vivi099** [emuPlace/emuThreeDS#69]
I cant type keybord or name on Story of season Games

**Comment by JIMMY523elcrak** [comment]
Use The touch screen

**Comment by official-antique** [comment]
@Vivi099, keyboard support was partially added in 1.0.5.4 to fix the crash but that version was removed due to bugs. Keyboar support and more will be added in 1.0.6.

**Comment by Vivi099** [comment]
Oh ok i got it thank you 👌
