### ISSUE TITLE
Would a 3DS home menu be possible?

### ISSUE THREAD

**Issue by Void48** [emuPlace/emuThreeDS#7]
https://youtu.be/0JD6_hzoNrU

**Comment by official-antique** [comment]
Absolutely, I could give that a try today.

**Comment by Efadd** [comment]
It's available in Citra desktop nightlies. I don't see why it can't be ported to emu3ds

**Comment by official-antique** [comment]
@Efadd guessing it's booting the emulator without a game?

**Comment by Efadd** [comment]
@official-antique Give me a second to pull out my laptop to show you

**Comment by Efadd** [comment]
https://youtu.be/oL_t86Vy4mc

**Comment by official-antique** [comment]
Closing as not something to be done on my end. All system apps can be run but will require dumping from a real system.

**Comment by Jarrius123** [comment]
How do I get it I need a ipa download link pls
