### ISSUE TITLE
crash when opening game

### ISSUE THREAD

**Issue by yoshidinn** [emuPlace/emuThreeDS#70]
rocking an iphone SE, game closes instantly with hle and JIT

**Comment by DanylLeStyle** [comment]
Diasble jit

**Comment by JIMMY523elcrak** [comment]
:v

**Comment by yoshidinn** [comment]
ive done that 😭

**Comment by yoshidinn** [comment]
crashes the very same way, is it a persona q issue?

**Comment by KWK083** [comment]
I use iphone7plus and have a same problem.

**Comment by JIMMY523elcrak** [comment]
I play MH 4 and The gane closed

**Comment by TraivonsWorld** [comment]
This happens to me as well I use an iPhone
