### ISSUE TITLE
The game is stretched across my screen

### ISSUE THREAD

**Issue by stossy11** [emuPlace/emuThreeDS#72]
https://imgur.com/a/i5k1ee5

Version 1.0.5.3

Controls work fine but its just wide and is wierd to play on

**Comment by arynrosh** [comment]
not ideal but heres a workaround...

rotate it veriticaly
rotate it back horizontally
open the settings icon>emulation>joystick for your controls to appear as intended

hopefully it gets fixed in 1.0.6.0
