### ISSUE TITLE
When I try to install it this happens

### ISSUE THREAD

**Issue by TraivonsWorld** [emuPlace/emuThreeDS#73]
![IMG_0104](https://github.com/emuPlace/emuThreeDS/assets/98612726/834bca56-61c0-4829-9a1c-0b7824b0d361)

**Comment by xontron** [comment]
what signing services are you using?

**Comment by Zoobmaball** [comment]
It's most likely because u already have 3 apps sideloaded, including AltStore (if you're using itj.

**Comment by TraivonsWorld** [comment]
@Zoobmaball when I tried this I hadn’t installed any

**Comment by TraivonsWorld** [comment]
@xontron when installing I used AnyTrans
