### ISSUE TITLE
Black screen when I launch the game

### ISSUE THREAD

**Issue by Broken6373** [emuPlace/emuThreeDS#75]
The rom is there, but the game remains with a black screen, what to do?

**Comment by Razhhaa** [comment]
I had the same Problem. Do you have an encrypted or decryptet Rom? With a decryptet it should work

**Comment by Broken6373** [comment]
J’ai regarder et apparemment installe les rom sur ce site romsfuns.com depuis ton pc tu fait un transfère avec icloud depuis ton pc vers ton iPhone tu telecharge et sa marche je sais pas pourquoi encore mais sa marche comme ça

**Comment by Razhhaa** [comment]
I dont speak french but if I understood it correctly via Google Translator, it works for you now, doesn't it?

**Comment by Broken6373** [comment]
Yes, excuse me, it works well on the romsfuns site
