### ISSUE TITLE
No Start/Select Button and Controller isn't working

### ISSUE THREAD

**Issue by Razhhaa** [emuPlace/emuThreeDS#76]
I've tried Ps4, XBox One and Razer Kishi Controller and none of them are working. In some Games I'm not even able to open the Inventory. Anybody know how to fix it?

**Comment by Pikachupikachup** [comment]
What game are you playing?

**Comment by Razhhaa** [comment]
Mario & Luigi Dream Team Bros.

**Comment by Pikachupikachup** [comment]
Try remapping the buttons

**Comment by Razhhaa** [comment]
I didn't know that I can do that. How?
