### ISSUE TITLE
not playable on iPhone 12 with backbone

### ISSUE THREAD

**Issue by ZabiTillT** [emuPlace/emuThreeDS#78]
Hello. iPhone 12 iOS 16.5 game version 1.0.5.3, 1.0.5.2. 1.0.5.1, 1.0.4 crashes to the desktop when starting the game and deletes the downloaded game. 1.0.3 in a horizontal position works but the double screen is only on the left. all versions delete games and saves when closed. used AltStore to install the application. games launched: Shovel_Knight, Super_Mario_3D_Land, New_Super_Mario_Bros._2. gamepad backbone

**Comment by official-antique** [comment]
What format are the games you are running? The app only deletes CIA roms once installed so nothing else should be affected.

**Comment by ZabiTillT** [comment]
the CIA image is not installed. I move the image CIA in format to the “rooms” folder, the image CIA appears in the application, then I open it and the application crashes to the desktop, I launch the application again and there is nothing there, the rooms folder is also empty, I check this in the iPhone files

**Comment by ZabiTillT** [comment]
3ds format works, nothing crashes. the only negative is that in a horizontal position there are two small screens in the middle, one above the other, how to change their location? one on the left, the other on the right or touch on the left and normal on the right or touch on the right and normal on the left?
