### ISSUE TITLE
Super Mario 3d land and other games that require a mii don’t work

### ISSUE THREAD

**Issue by TheOfficialSin** [emuPlace/emuThreeDS#8]
Super mario 3d land and other games that require a mii but once you get to the mii part the emulator crashes.

**Comment by TheOfficialSin** [comment]
This also applies to rinsuki’s emulator

**Comment by Mario2425** [comment]
Yeah you cant even create a mii because of the touch screen support doesnt added yet.

**Comment by official-antique** [comment]
Mii's will be supported in the SwiftUI release coming soon, keep an eye out on the `swiftui-rework` branch! Closing this for now though to clean up the issues a bit.
