### ISSUE TITLE
[v1.0.6.1] Shows iOS UI on iPadOS and can’t select games

### ISSUE THREAD

**Issue by AshZadePM** [emuPlace/emuThreeDS#90]
Latest public build displays correctly on iPad but [v1.0.6.1] displays as an iOS app. 

Also I can’t select anything.

**Comment by PatchedHole** [comment]
wait what, its out already

**Comment by CottonWoolee** [comment]
You have to select the game first, then click the "emulation" tab to switch to game screen.

**Comment by AshZadePM** [comment]
> You have to select the game first, then click the "emulation" tab to switch to game screen.

They launched the game, thanks. 

Still unplayable with the UI scaling issue.

**Comment by AshZadePM** [comment]
> > > You have to select the game first, then click the "emulation" tab to switch to game screen.
> > 
> > 
> > They launched the game, thanks.
> > Still unplayable with the UI scaling issue.
> 
> Yes, in my situation, the game screen has correct aspect ratio only in landscape mode*, no matter whether the device is placed horizontally or vertically.
> 
> * There is a rotation button in the lower right corner of the screen to switch between landscape or portrait mode.

Ah thanks, that solved that problem. Last one is the UI scaling. The controls are huge and the joystick covers a lot of the screen.
