### ISSUE TITLE
No control buttons

### ISSUE THREAD

**Issue by T4ts** [emuPlace/emuThreeDS#92]
I just downloaded the app. When I open a ROM, the game plays out but there’s no buttons whatsoever. When I stopped emulating, the buttons appeared in the game selection menu… Why?

**Comment by T4ts** [comment]
Okay the buttons are fixed on 1.0.5.3 but now there is no up down let right nor a joystick?

**Comment by official-antique** [comment]
Hey @T4ts, sorry for the issues in v1.0.5.3, these are all fixed in v1.0.6.1 now but that version is only available to Canary tier members on **[BMAC](https://buymeacoffee.com/antique)** at the moment (v1.0.6.2 will make v1.0.6.2 public).
