### ISSUE TITLE
Important things to fix quickly 

### ISSUE THREAD

**Issue by NurK41** [emuPlace/emuThreeDS#96]
1)now it doesn’t work on iPad (it became a iPhone only app)
2)the emulator setting zone makes crash the app
3)you have to add Roms language settings
4)you have to add more settings(for emulation,graphics,audio,buttons ecc.)
5)now the rooms don’t even start
6)you have to add full Nintendo 3ds buttons(maybe include also the C-stick)
I hope you fix this in some hours/days ,but thank you to continuing developing this<3

**Comment by ansinerd** [comment]
> New version don't work on my iPad(M1 iOS 15.1)too

Bcz the minimum required version is 16.0
Antique will change jt soon

**Comment by Zoobmaball** [comment]
> > New version don't work on my iPad(M1 iOS 15.1)too
> 
> 
> 
> Bcz the minimum required version is 16.0
> 
> Antique will change jt soon

Mine won't work and I am on latest version

**Comment by CharlieKreig** [comment]
> > New version don't work on my iPad(M1 iOS 15.1)too
> 
> 
> 
> Bcz the minimum required version is 16.0
> 
> Antique will change jt soon

Previous version 1.0.5.3 working perfect, for new version required iOS changed?
