### ISSUE TITLE
[v1.0.6.2] Canary build issues : That needs fixing soon

### ISSUE THREAD

**Issue by ansinerd** [emuPlace/emuThreeDS#97]
Greetings, quite happy with the latest canary build, however there are many things that still need fixing.
I want to mention the issues that need urgent fixing that are ruining the game play experience.

1. The R and L buttons are there but still not functional, touch isn’t registered. Thus making it quite useless. Also we need to change the position of R and L button, possibly on top on either side and please make them transparent, instead of opaque. In games like Metroid u need to use the stick and simultaneously press R button, it’s so difficult to execute it in current position. Please watch how android people and even egg3ds people have implemented it, their controls feel much more natural and more practical than our approach. I hope you can even take public voting if unsure and decide how you wanna do it.
3. The Opaque thumb stick is still quite intrusive in nature, its humble request to please add egg3ds like transparent stick.
4. The SAVE and LOAD state need to make a come back soon.
5. The emulator still has layout issues, every time you change layout you need to rotate your device in order to implement it.
6. The resolution tab works but each time you change resolution you need to restart the app else the effects won’t come into action.
7. The performance on HLE has regressed compared to earlier builds, even on lowest resolution the emulation is super slow compared to earlier times.
8. Lack of physical controller support is quite frustrating, I tried Xbox controller, dual sense controller and backbone controller and none of them worked. Although N3ds would crash if I attach backbone one controller and press any key. Workaround, there should be physical controller support in upcoming builds and automatic disappearance of on screen controls if the emulator detects attachment of physical controller.
9. Random crashing while changing rom.
10. Random slowdown but that’s related to original Citra build and I don’t think we can do much about it.

Some positives and pros of the emulator :
1. The return of HLE mode is highly appreciated
2. The option of setting customised resolution is highly welcome move.
3. The power devices like iPad Pro 2021 can actually go at 10x resolution and still be playable, gorgeous looks.
4. The speed of emulation is good too.
5. The touch is registering in the menu now, now we can select rom by touching it.
6. The screen layout is almost perfect now, much lesser screen wasting on 12.9 inch iPad, and on iPhone 13 the screen layout is perfect on single screen, main screen, mobile landscape and portrait mode, side by side should have 70-30 layout instead of current 50-50. 
7. This build feels optimised for larger devices like iPad Pro. 

If possible have a look at PPSSPP touch control codes and how they behave in game, they feel much more comfortable and perhaps the best on screen controls on ios.
Also try for save and load settings, it will make much bigger difference for so many people.

Overall a very solid base to go from.
Overall much much better, couldn’t have imagined such progress in short time, your work has been truly marvellous and I am glad you are here and you are giving your efforts for this port. I thank you so much.

**Comment by AshZadePM** [comment]
Agreed with the Pros.

Adding two more bugs from my list:
1. No in-game music in Pokemon X. This stopped working in 1.0.6.x.
2. Library doesn't display in portrait on iPad by default. I have to open the side menu. Maybe not a bug, but not a good experience.

**Comment by ansinerd** [comment]
> Agreed with the Pros.
> 
> Adding two more bugs from my list:
> 
> 1. No in-game music in Pokemon X. This stopped working in 1.0.6.x.
> 2. Library doesn't display in portrait on iPad by default. I have to open the side menu. Maybe not a bug, but not a good experience.

Completely agreed. Though audio works for me in mario kart and super mario but i dint check much.

2. u r right library doesn’t display on ipad. Needs fixing.
