### ISSUE TITLE
V.1.0.6.1 bugs

### ISSUE THREAD

**Issue by xdccrlz** [emuPlace/emuThreeDS#99]
1. Code need fix for iPhone 13 Pro Max - building errors
2. External gamepad no working
3. Black screen in the landscape mode
4. No resolution option
5. No HLE option

**Comment by official-antique** [comment]
1. Are you trying to build from source? What does this mean.
2. I'm unsure if the physical controller code is there currently but will add it for v1.0.6.3.
3. This appears to be fixed in v1.0.6.2.
4 and 5. These settings are available in v1.0.6.2.

**Comment by xdccrlz** [comment]
Build from source give an errors "coreaudio_sink.cpp Implicit instantiation of undefined template 'std::vector<std::string>'".
setting header #include <vector> solve this issue.
